## Pandas Basic

In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("train.csv")

In [3]:
df

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,1,60,RL,65.0,8450,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2008,WD,Normal,208500
1,2,20,RL,80.0,9600,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,5,2007,WD,Normal,181500
2,3,60,RL,68.0,11250,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,9,2008,WD,Normal,223500
3,4,70,RL,60.0,9550,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2006,WD,Abnorml,140000
4,5,60,RL,84.0,14260,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,12,2008,WD,Normal,250000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1455,1456,60,RL,62.0,7917,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,8,2007,WD,Normal,175000
1456,1457,20,RL,85.0,13175,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,MnPrv,NaN,0,2,2010,WD,Normal,210000
1457,1458,70,RL,66.0,9042,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,GdPrv,Shed,2500,5,2010,WD,Normal,266500
1458,1459,20,RL,68.0,9717,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,4,2010,WD,Normal,142125
1459,1460,20,RL,75.0,9937,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,6,2008,WD,Normal,147500

In [4]:
df.head(5)

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,1,60,RL,65.0,8450,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2008,WD,Normal,208500
1,2,20,RL,80.0,9600,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,5,2007,WD,Normal,181500
2,3,60,RL,68.0,11250,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,9,2008,WD,Normal,223500
3,4,70,RL,60.0,9550,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2006,WD,Abnorml,140000
4,5,60,RL,84.0,14260,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,12,2008,WD,Normal,250000

In [5]:
df.tail()

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
1455,1456,60,RL,62.0,7917,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,8,2007,WD,Normal,175000
1456,1457,20,RL,85.0,13175,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,MnPrv,NaN,0,2,2010,WD,Normal,210000
1457,1458,70,RL,66.0,9042,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,GdPrv,Shed,2500,5,2010,WD,Normal,266500
1458,1459,20,RL,68.0,9717,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,4,2010,WD,Normal,142125
1459,1460,20,RL,75.0,9937,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,6,2008,WD,Normal,147500

In [6]:
type(df)

pandas.core.frame.DataFrame

In [7]:
newrecords = df.head(6)

In [8]:
newrecords

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,1,60,RL,65.0,8450,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2008,WD,Normal,208500
1,2,20,RL,80.0,9600,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,5,2007,WD,Normal,181500
2,3,60,RL,68.0,11250,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,9,2008,WD,Normal,223500
3,4,70,RL,60.0,9550,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2006,WD,Abnorml,140000
4,5,60,RL,84.0,14260,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,12,2008,WD,Normal,250000
5,6,50,RL,85.0,14115,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,MnPrv,Shed,700,10,2009,WD,Normal,143000

In [9]:
newrecords.to_csv("newrecords.csv")

In [10]:
pd.read_csv("newrecords.csv")

,Unnamed: 0,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,0,1,60,RL,65.0,8450,Pave,NaN,Reg,Lvl,...,0,NaN,NaN,NaN,0,2,2008,WD,Normal,208500
1,1,2,20,RL,80.0,9600,Pave,NaN,Reg,Lvl,...,0,NaN,NaN,NaN,0,5,2007,WD,Normal,181500
2,2,3,60,RL,68.0,11250,Pave,NaN,IR1,Lvl,...,0,NaN,NaN,NaN,0,9,2008,WD,Normal,223500
3,3,4,70,RL,60.0,9550,Pave,NaN,IR1,Lvl,...,0,NaN,NaN,NaN,0,2,2006,WD,Abnorml,140000
4,4,5,60,RL,84.0,14260,Pave,NaN,IR1,Lvl,...,0,NaN,NaN,NaN,0,12,2008,WD,Normal,250000
5,5,6,50,RL,85.0,14115,Pave,NaN,IR1,Lvl,...,0,NaN,MnPrv,Shed,700,10,2009,WD,Normal,143000

In [11]:
## see appended columns in last ## Pls scroll
## Skipped rows
pd.read_csv("newrecords.csv",header=None,names=['Sachin','Virat','JP','Dhoni'],skiprows=[3,4])

,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,Sachin,Virat,JP,Dhoni
NaN,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,LotConfig,LandSlope,Neighborhood,Condition1,Condition2,BldgType,HouseStyle,OverallQual,OverallCond,YearBuilt,YearRemodAdd,RoofStyle,RoofMatl,Exterior1st,Exterior2nd,MasVnrType,MasVnrArea,ExterQual,ExterCond,Foundation,BsmtQual,BsmtCond,BsmtExposure,BsmtFinType1,BsmtFinSF1,BsmtFinType2,BsmtFinSF2,BsmtUnfSF,TotalBsmtSF,Heating,HeatingQC,CentralAir,Electrical,1stFlrSF,2ndFlrSF,LowQualFinSF,GrLivArea,BsmtFullBath,BsmtHalfBath,FullBath,HalfBath,BedroomAbvGr,KitchenAbvGr,KitchenQual,TotRmsAbvGrd,Functional,Fireplaces,FireplaceQu,GarageType,GarageYrBlt,GarageFinish,GarageCars,GarageArea,GarageQual,GarageCond,PavedDrive,WoodDeckSF,OpenPorchSF,EnclosedPorch,3SsnPorch,ScreenPorch,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0.0,1,60,RL,65.0,8450,Pave,NaN,Reg,Lvl,AllPub,Inside,Gtl,CollgCr,Norm,Norm,1Fam,2Story,7,5,2003,2003,Gable,CompShg,VinylSd,VinylSd,BrkFace,196.0,Gd,TA,PConc,Gd,TA,No,GLQ,706,Unf,0,150,856,GasA,Ex,Y,SBrkr,856,854,0,1710,1,0,2,1,3,1,Gd,8,Typ,0,NaN,Attchd,2003.0,RFn,2,548,TA,TA,Y,0,61,0,0,0,0,NaN,NaN,NaN,0,2,2008,WD,Normal,208500
1.0,2,20,RL,80.0,9600,Pave,NaN,Reg,Lvl,AllPub,FR2,Gtl,Veenker,Feedr,Norm,1Fam,1Story,6,8,1976,1976,Gable,CompShg,MetalSd,MetalSd,None,0.0,TA,TA,CBlock,Gd,TA,Gd,ALQ,978,Unf,0,284,1262,GasA,Ex,Y,SBrkr,1262,0,0,1262,0,1,2,0,3,1,TA,6,Typ,1,TA,Attchd,1976.0,RFn,2,460,TA,TA,Y,298,0,0,0,0,0,NaN,NaN,NaN,0,5,2007,WD,Normal,181500
4.0,5,60,RL,84.0,14260,Pave,NaN,IR1,Lvl,AllPub,FR2,Gtl,NoRidge,Norm,Norm,1Fam,2Story,8,5,2000,2000,Gable,CompShg,VinylSd,VinylSd,BrkFace,350.0,Gd,TA,PConc,Gd,TA,Av,GLQ,655,Unf,0,490,1145,GasA,Ex,Y,SBrkr,1145,1053,0,2198,1,0,2,1,4,1,Gd,9,Typ,1,TA,Attchd,2000.0,RFn,3,836,TA,TA,Y,192,84,0,0,0,0,NaN,NaN,NaN,0,12,2008,WD,Normal,250000
5.0,6,50,RL,85.0,14115,Pave,NaN,IR1,Lvl,AllPub,Inside,Gtl,Mitchel,Norm,Norm,1Fam,1.5Fin,5,5,1993,1995,Gable,CompShg,VinylSd,VinylSd,None,0.0,TA,TA,Wood,Gd,TA,No,GLQ,732,Unf,0,64,796,GasA,Ex,Y,SBrkr,796,566,0,1362,1,0,1,1,1,1,TA,5,Typ,0,NaN,Attchd,1993.0,Unf,2,480,TA,TA,Y,40,30,0,320,0,0,NaN,MnPrv,Shed,700,10,2009,WD,Normal,143000

In [12]:
## na_values will replace the particular value as NaN
df = pd.read_csv("train.csv",na_values=['RL','IR1'])
df

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,1,60,NaN,65.0,8450,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2008,WD,Normal,208500
1,2,20,NaN,80.0,9600,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,5,2007,WD,Normal,181500
2,3,60,NaN,68.0,11250,Pave,NaN,NaN,Lvl,AllPub,...,0,NaN,NaN,NaN,0,9,2008,WD,Normal,223500
3,4,70,NaN,60.0,9550,Pave,NaN,NaN,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2006,WD,Abnorml,140000
4,5,60,NaN,84.0,14260,Pave,NaN,NaN,Lvl,AllPub,...,0,NaN,NaN,NaN,0,12,2008,WD,Normal,250000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1455,1456,60,NaN,62.0,7917,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,8,2007,WD,Normal,175000
1456,1457,20,NaN,85.0,13175,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,MnPrv,NaN,0,2,2010,WD,Normal,210000
1457,1458,70,NaN,66.0,9042,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,GdPrv,Shed,2500,5,2010,WD,Normal,266500
1458,1459,20,NaN,68.0,9717,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,4,2010,WD,Normal,142125
1459,1460,20,NaN,75.0,9937,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,6,2008,WD,Normal,147500

In [13]:
##It only gives description of numerical data
# min is 0th percentile
# max is 100th percentile
# percentile: sort the column first in ascending order then calculate percentile
## Data which is available at 25percentile it shows that
## It represents indexes
## you can say like 1460(count) datas id 50th percentile would be 730
df.describe()

,Id,MSSubClass,LotFrontage,LotArea,OverallQual,OverallCond,YearBuilt,YearRemodAdd,MasVnrArea,BsmtFinSF1,...,WoodDeckSF,OpenPorchSF,EnclosedPorch,3SsnPorch,ScreenPorch,PoolArea,MiscVal,MoSold,YrSold,SalePrice
count,1460.000000,1460.000000,1201.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1452.000000,1460.000000,...,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000
mean,730.500000,56.897260,70.049958,10516.828082,6.099315,5.575342,1971.267808,1984.865753,103.685262,443.639726,...,94.244521,46.660274,21.954110,3.409589,15.060959,2.758904,43.489041,6.321918,2007.815753,180921.195890
std,421.610009,42.300571,24.284752,9981.264932,1.382997,1.112799,30.202904,20.645407,181.066207,456.098091,...,125.338794,66.256028,61.119149,29.317331,55.757415,40.177307,496.123024,2.703626,1.328095,79442.502883
min,1.000000,20.000000,21.000000,1300.000000,1.000000,1.000000,1872.000000,1950.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,2006.000000,34900.000000
25%,365.750000,20.000000,59.000000,7553.500000,5.000000,5.000000,1954.000000,1967.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,5.000000,2007.000000,129975.000000
50%,730.500000,50.000000,69.000000,9478.500000,6.000000,5.000000,1973.000000,1994.000000,0.000000,383.500000,...,0.000000,25.000000,0.000000,0.000000,0.000000,0.000000,0.000000,6.000000,2008.000000,163000.000000
75%,1095.250000,70.000000,80.000000,11601.500000,7.000000,6.000000,2000.000000,2004.000000,166.000000,712.250000,...,168.000000,68.000000,0.000000,0.000000,0.000000,0.000000,0.000000,8.000000,2009.000000,214000.000000
max,1460.000000,190.000000,313.000000,215245.000000,10.000000,9.000000,2010.000000,2010.000000,1600.000000,5644.000000,...,857.000000,547.000000,552.000000,508.000000,480.000000,738.000000,15500.000000,12.000000,2010.000000,755000.000000

In [14]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1460 entries, 0 to 1459
Data columns (total 81 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Id             1460 non-null   int64
 1   MSSubClass     1460 non-null   int64
 2   MSZoning       309 non-null    object
 3   LotFrontage    1201 non-null   float64
 4   LotArea        1460 non-null   int64
 5   Street         1460 non-null   object
 6   Alley          91 non-null     object
 7   LotShape       976 non-null    object
 8   LandContour    1460 non-null   object
 9   Utilities      1460 non-null   object
 10  LotConfig      1460 non-null   object
 11  LandSlope      1460 non-null   object
 12  Neighborhood   1460 non-null   object
 13  Condition1     1460 non-null   object
 14  Condition2     1460 non-null   object
 15  BldgType       1460 non-null   object
 16  HouseStyle     1460 non-null   object
 17  OverallQual    1460 non-null   int64
 18  OverallCond    1460 non-null   int64
 19  YearBuilt      1460 non-null   int64
 20  YearRemodAdd   1460 non-null   int64
 21  RoofStyle      1460 non-null   object
 22  RoofMatl       1460 non-null   object
 23  Exterior1st    1460 non-null   object
 24  Exterior2nd    1460 non-null   object
 25  MasVnrType     1452 non-null   object
 26  MasVnrArea     1452 non-null   float64
 27  ExterQual      1460 non-null   object
 28  ExterCond      1460 non-null   object
 29  Foundation     1460 non-null   object
 30  BsmtQual       1423 non-null   object
 31  BsmtCond       1423 non-null   object
 32  BsmtExposure   1422 non-null   object
 33  BsmtFinType1   1423 non-null   object
 34  BsmtFinSF1     1460 non-null   int64
 35  BsmtFinType2   1422 non-null   object
 36  BsmtFinSF2     1460 non-null   int64
 37  BsmtUnfSF      1460 non-null   int64
 38  TotalBsmtSF    1460 non-null   int64
 39  Heating        1460 non-null   object
 40  HeatingQC      1460 non-null   object
 41  CentralAir     1460 non-null   object
 42  Electrical     1459 non-null   object
 43  1stFlrSF       1460 non-null   int64
 44  2ndFlrSF       1460 non-null   int64
 45  LowQualFinSF   1460 non-null   int64
 46  GrLivArea      1460 non-null   int64
 47  BsmtFullBath   1460 non-null   int64
 48  BsmtHalfBath   1460 non-null   int64
 49  FullBath       1460 non-null   int64
 50  HalfBath       1460 non-null   int64
 51  BedroomAbvGr   1460 non-null   int64
 52  KitchenAbvGr   1460 non-null   int64
 53  KitchenQual    1460 non-null   object
 54  TotRmsAbvGrd   1460 non-null   int64
 55  Functional     1460 non-null   object
 56  Fireplaces     1460 non-null   int64
 57  FireplaceQu    770 non-null    object
 58  GarageType     1379 non-null   object
 59  GarageYrBlt    1379 non-null   float64
 60  GarageFinish   1379 non-null   object
 61  GarageCars     1460 non-null   int64
 62  GarageArea     1460 non-null   int64
 63  GarageQual     1379 non-null   object
 64  GarageCond     1379 non-null   object
 65  PavedDrive     1460 non-null   object
 66  WoodDeckSF     1460 non-null   int64
 67  OpenPorchSF    1460 non-null   int64
 68  EnclosedPorch  1460 non-null   int64
 69  3SsnPorch      1460 non-null   int64
 70  ScreenPorch    1460 non-null   int64
 71  PoolArea       1460 non-null   int64
 72  PoolQC         7 non-null      object
 73  Fence          281 non-null    object
 74  MiscFeature    54 non-null     object
 75  MiscVal        1460 non-null   int64
 76  MoSold         1460 non-null   int64
 77  YrSold         1460 non-null   int64
 78  SaleType       1460 non-null   object
 79  SaleCondition  1460 non-null   object
 80  SalePrice      1460 non-null   int64
dtypes: float64(3), int64(35), object(43)
memory usage: 924.0+ KB

In [15]:
df.dtypes

Id                 int64
MSSubClass         int64
MSZoning          object
LotFrontage      float64
LotArea            int64
                  ...
MoSold             int64
YrSold             int64
SaleType          object
SaleCondition     object
SalePrice          int64
Length: 81, dtype: object

In [16]:
## Here columns parameter behaves like which columns you need
df.to_csv("newrecordswith3columns.csv",index=False,header=False,sep="#",columns=['YearBuilt',"SaleCondition","SalePrice"])

In [17]:
pd.read_csv("newrecordswith3columns.csv",sep="#")

      2003   Normal  208500
0     1976   Normal  181500
1     2001   Normal  223500
2     1915  Abnorml  140000
3     2000   Normal  250000
4     1993   Normal  143000
...    ...      ...     ...
1454  1999   Normal  175000
1455  1978   Normal  210000
1456  1941   Normal  266500
1457  1950   Normal  142125
1458  1965   Normal  147500

[1459 rows x 3 columns]

In [18]:
df = pd.read_csv("train.csv")
df

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,1,60,RL,65.0,8450,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2008,WD,Normal,208500
1,2,20,RL,80.0,9600,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,5,2007,WD,Normal,181500
2,3,60,RL,68.0,11250,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,9,2008,WD,Normal,223500
3,4,70,RL,60.0,9550,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2006,WD,Abnorml,140000
4,5,60,RL,84.0,14260,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,12,2008,WD,Normal,250000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1455,1456,60,RL,62.0,7917,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,8,2007,WD,Normal,175000
1456,1457,20,RL,85.0,13175,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,MnPrv,NaN,0,2,2010,WD,Normal,210000
1457,1458,70,RL,66.0,9042,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,GdPrv,Shed,2500,5,2010,WD,Normal,266500
1458,1459,20,RL,68.0,9717,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,4,2010,WD,Normal,142125
1459,1460,20,RL,75.0,9937,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,6,2008,WD,Normal,147500

In [19]:
df.tail(5)

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
1455,1456,60,RL,62.0,7917,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,8,2007,WD,Normal,175000
1456,1457,20,RL,85.0,13175,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,MnPrv,NaN,0,2,2010,WD,Normal,210000
1457,1458,70,RL,66.0,9042,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,GdPrv,Shed,2500,5,2010,WD,Normal,266500
1458,1459,20,RL,68.0,9717,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,4,2010,WD,Normal,142125
1459,1460,20,RL,75.0,9937,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,6,2008,WD,Normal,147500

In [20]:
#To list columns
df.columns

Index(['Id', 'MSSubClass', 'MSZoning', 'LotFrontage', 'LotArea', 'Street',
       'Alley', 'LotShape', 'LandContour', 'Utilities', 'LotConfig',
       'LandSlope', 'Neighborhood', 'Condition1', 'Condition2', 'BldgType',
       'HouseStyle', 'OverallQual', 'OverallCond', 'YearBuilt', 'YearRemodAdd',
       'RoofStyle', 'RoofMatl', 'Exterior1st', 'Exterior2nd', 'MasVnrType',
       'MasVnrArea', 'ExterQual', 'ExterCond', 'Foundation', 'BsmtQual',
       'BsmtCond', 'BsmtExposure', 'BsmtFinType1', 'BsmtFinSF1',
       'BsmtFinType2', 'BsmtFinSF2', 'BsmtUnfSF', 'TotalBsmtSF', 'Heating',
       'HeatingQC', 'CentralAir', 'Electrical', '1stFlrSF', '2ndFlrSF',
       'LowQualFinSF', 'GrLivArea', 'BsmtFullBath', 'BsmtHalfBath', 'FullBath',
       'HalfBath', 'BedroomAbvGr', 'KitchenAbvGr', 'KitchenQual',
       'TotRmsAbvGrd', 'Functional', 'Fireplaces', 'FireplaceQu', 'GarageType',
       'GarageYrBlt', 'GarageFinish', 'GarageCars', 'GarageArea', 'GarageQual',
       'GarageCond', 'PavedDrive', 'WoodDeckSF', 'OpenPorchSF',
       'EnclosedPorch', '3SsnPorch', 'ScreenPorch', 'PoolArea', 'PoolQC',
       'Fence', 'MiscFeature', 'MiscVal', 'MoSold', 'YrSold', 'SaleType',
       'SaleCondition', 'SalePrice'],
      dtype='object')

In [21]:
df['LandSlope']

0       Gtl
1       Gtl
2       Gtl
3       Gtl
4       Gtl
       ...
1455    Gtl
1456    Gtl
1457    Gtl
1458    Gtl
1459    Gtl
Name: LandSlope, Length: 1460, dtype: object

In [22]:
## to retrive particular data from column
df['LandSlope'][1456]

'Gtl'

In [23]:
## pandas has 2 types series and dataframe
## series is like from entire data 1 column or 1 row is considered as series
type(df['LandSlope'])

pandas.core.series.Series

In [24]:
## To convert it into dataframe
df[['GarageCars']]

      GarageCars
0              2
1              2
2              2
3              3
4              3
...          ...
1455           2
1456           2
1457           1
1458           1
1459           1

[1460 rows x 1 columns]

In [25]:
## when you pass your column name into a list then your data will be transformed in dataframe
type(df[['GarageCars']])

pandas.core.frame.DataFrame

In [26]:
## to get multiple data
df[['GarageCars','GarageFinish','Utilities']]

      GarageCars GarageFinish Utilities
0              2          RFn    AllPub
1              2          RFn    AllPub
2              2          RFn    AllPub
3              3          Unf    AllPub
4              3          RFn    AllPub
...          ...          ...       ...
1455           2          RFn    AllPub
1456           2          Unf    AllPub
1457           1          RFn    AllPub
1458           1          Unf    AllPub
1459           1          Fin    AllPub

[1460 rows x 3 columns]

## Excel

In [27]:
!pip install xlrd

Requirement already satisfied: xlrd in c:\users\91706\anaconda3\envs\ai\lib\site-packages (2.0.1)

In [28]:
!pip install openpyxl

Requirement already satisfied: openpyxl in c:\users\91706\anaconda3\envs\ai\lib\site-packages (3.0.7)
Requirement already satisfied: et-xmlfile in c:\users\91706\anaconda3\envs\ai\lib\site-packages (from openpyxl) (1.1.0)

In [29]:
df = pd.read_excel("C:/Users/91706/Downloads/student-data.xlsx")
df.head(6)

,Segment,Country,Product,Discount Band,Units Sold,Manufacturing Price,Sale Price,Gross Sales,Discounts,Sales,COGS,Profit,Date,Month Number,Month Name,Year
0,Government,Canada,Carretera,None,1618.5,3,20,32370.0,0.0,32370.0,16185.0,16185.0,2014-01-01,1,January,2014
1,Government,Germany,Carretera,None,1321.0,3,20,26420.0,0.0,26420.0,13210.0,13210.0,2014-01-01,1,January,2014
2,Midmarket,France,Carretera,None,2178.0,3,15,32670.0,0.0,32670.0,21780.0,10890.0,2014-06-01,6,June,2014
3,Midmarket,Germany,Carretera,None,888.0,3,15,13320.0,0.0,13320.0,8880.0,4440.0,2014-06-01,6,June,2014
4,Midmarket,Mexico,Carretera,None,2470.0,3,15,37050.0,0.0,37050.0,24700.0,12350.0,2014-06-01,6,June,2014
5,Government,Germany,Carretera,None,1513.0,3,350,529550.0,0.0,529550.0,393380.0,136170.0,2014-12-01,12,December,2014

In [30]:
df = pd.read_excel("C:/Users/91706/Downloads/student-data.xlsx",sheet_name='EmpData')
df.head(6)

,Emp ID,Name Prefix,First Name,Middle Initial,Last Name,Gender,E Mail,Father's Name,Mother's Name,Mother's Maiden Name,...,SSN,Phone No.,Place Name,County,City,State,Zip,Region,User Name,Password
0,677509,Drs.,Lois,H,Walker,F,lois.walker@hotmail.com,Donald Walker,Helen Walker,Lewis,...,467-99-4677,303-572-8492,Denver,Denver,Denver,CO,80224,West,lhwalker,DCa}.T}X:v?NP
1,940761,Ms.,Brenda,S,Robinson,F,brenda.robinson@gmail.com,Raymond Robinson,Judy Robinson,Perry,...,537-71-4566,225-945-4954,Stonewall,De Soto,Stonewall,LA,71078,South,bsrobinson,TCo\j#Zg;SQ~o
2,428945,Dr.,Joe,W,Robinson,M,joe.robinson@gmail.com,Scott Robinson,Stephanie Robinson,Taylor,...,025-92-3584,219-904-2161,Michigantown,Clinton,Michigantown,IN,46057,Midwest,jwrobinson,GO4$J8MiEh[A
3,408351,Drs.,Diane,I,Evans,F,diane.evans@yahoo.com,Jason Evans,Michelle Evans,Allen,...,314-35-9851,215-793-6791,Hydetown,Crawford,Hydetown,PA,16328,Northeast,dievans,0gGRtp1HfL<r5
4,193819,Mr.,Benjamin,R,Russell,M,benjamin.russell@charter.net,Gregory Russell,Elizabeth Russell,Nelson,...,121-98-7248,262-404-2252,Fremont,Waupaca,Fremont,WI,54940,Midwest,brrussell,Rd<Y8cp!@R;*%F
5,499687,Mr.,Patrick,F,Bailey,M,patrick.bailey@aol.com,Ralph Bailey,Laura Bailey,Henderson,...,439-99-7721,319-812-6957,Macksburg,Madison,Macksburg,IA,50155,Midwest,pfbailey,K7&5aY/*

## HTML

In [31]:
## It basically tries to find <tr><tb> tag bydefault
df2 = pd.read_html("https://www.basketball-reference.com/players/i/ibakase01.html?utm_source=direct&utm_medium=Share&utm_campaign=ShareTool")

In [32]:
type(df2)

list

In [33]:
len(df2)

6

In [34]:
df2[0]

,Season,Age,Team,Lg,Pos,G,GS,MP,FG,FGA,...,FT%,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS
0,2008-09,19.0,Did Not Play (other pro league—Spain),Did Not Play (other pro league—Spain),Did Not Play (other pro league—Spain),Did Not Play (other pro league—Spain),Did Not Play (other pro league—Spain),Did Not Play (other pro league—Spain),Did Not Play (other pro league—Spain),Did Not Play (other pro league—Spain),...,Did Not Play (other pro league—Spain),Did Not Play (other pro league—Spain),Did Not Play (other pro league—Spain),Did Not Play (other pro league—Spain),Did Not Play (other pro league—Spain),Did Not Play (other pro league—Spain),Did Not Play (other pro league—Spain),Did Not Play (other pro league—Spain),Did Not Play (other pro league—Spain),Did Not Play (other pro league—Spain)
1,2009-10,20.0,OKC,NBA,PF,73,0,18.1,2.8,5.1,...,.630,1.9,3.5,5.4,0.1,0.3,1.3,0.9,2.7,6.3
2,2010-11,21.0,OKC,NBA,PF,82,44,27.0,4.1,7.5,...,.750,2.6,5.0,7.6,0.3,0.4,2.4,0.9,3.3,9.9
3,2011-12,22.0,OKC,NBA,PF,66,66,27.2,4.0,7.4,...,.661,2.9,4.6,7.5,0.4,0.5,3.7,1.2,2.7,9.1
4,2012-13,23.0,OKC,NBA,PF,80,80,31.1,5.6,9.7,...,.749,2.8,4.9,7.7,0.5,0.4,3.0,1.6,2.7,13.2
5,2013-14,24.0,OKC,NBA,PF,81,81,32.9,6.5,12.1,...,.784,2.8,6.0,8.8,1.0,0.5,2.7,1.5,2.9,15.1
6,2014-15,25.0,OKC,NBA,PF,64,64,33.1,5.8,12.3,...,.836,2.1,5.7,7.8,0.9,0.5,2.4,1.5,3.0,14.3
7,2015-16,26.0,OKC,NBA,PF,78,78,32.1,5.3,11.1,...,.752,1.8,5.0,6.8,0.8,0.5,1.9,1.4,2.7,12.6
8,2016-17,27.0,TOT,NBA,PF,79,79,30.7,6.0,12.4,...,.856,1.6,5.2,6.8,0.9,0.5,1.6,1.3,2.7,14.8
9,2016-17,27.0,ORL,NBA,PF,56,56,30.5,6.1,12.6,...,.846,1.8,5.0,6.8,1.1,0.6,1.6,1.2,2.5,15.1
10,2016-17,27.0,TOR,NBA,PF,23,23,31.0,5.6,12.1,...,.882,1.3,5.5,6.8,0.7,0.3,1.4,1.7,3.3,14.2
11,2017-18,28.0,TOR,NBA,PF,76,76,27.5,5.0,10.3,...,.797,1.0,5.3,6.3,0.8,0.4,1.3,1.2,2.8,12.6
12,2018-19,29.0,TOR,NBA,C,74,51,27.2,6.3,11.9,...,.763,2.1,6.0,8.1,1.3,0.4,1.4,1.5,2.9,15.0
13,2019-20,30.0,TOR,NBA,C,55,27,27.0,6.2,12.2,...,.718,2.1,6.1,8.2,1.4,0.5,0.8,2.0,2.8,15.4
14,2020-21,31.0,LAC,NBA,C,41,39,23.3,4.5,8.9,...,.811,1.8,4.9,6.7,1.8,0.2,1.1,1.1,1.9,11.1
15,Career,NaN,NaN,NBA,NaN,849,685,28.3,5.2,10.1,...,.759,2.1,5.2,7.3,0.8,0.4,2.0,1.3,2.8,12.5
16,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,7 seasons,NaN,OKC,NBA,NaN,524,413,28.8,4.9,9.3,...,.745,2.4,5.0,7.4,0.6,0.4,2.5,1.3,2.8,11.6
18,4 seasons,NaN,TOR,NBA,NaN,228,177,27.6,5.8,11.4,...,.768,1.7,5.7,7.4,1.1,0.4,1.2,1.5,2.8,14.2
19,1 season,NaN,ORL,NBA,NaN,56,56,30.5,6.1,12.6,...,.846,1.8,5.0,6.8,1.1,0.6,1.6,1.2,2.5,15.1
20,1 season,NaN,LAC,NBA,NaN,41,39,23.3,4.5,8.9,...,.811,1.8,4.9,6.7,1.8,0.2,1.1,1.1,1.9,11.1

In [35]:
df2[3]

,Season,Age,Team,Lg,Pos,G,GS,MP,FG,FGA,...,FT%,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS
0,2009-10,20.0,OKC,NBA,PF,6.0,0.0,153.0,20.0,35.0,...,0.700,13.0,26.0,39.0,2.0,2.0,12.0,6.0,19.0,47.0
1,2010-11,21.0,OKC,NBA,PF,17.0,17.0,490.0,67.0,145.0,...,0.825,47.0,77.0,124.0,3.0,4.0,52.0,21.0,64.0,167.0
2,2011-12,22.0,OKC,NBA,PF,20.0,20.0,569.0,84.0,159.0,...,0.722,47.0,68.0,115.0,12.0,11.0,59.0,11.0,57.0,195.0
3,2012-13,23.0,OKC,NBA,PF,11.0,11.0,366.0,59.0,135.0,...,0.792,39.0,53.0,92.0,8.0,0.0,33.0,7.0,38.0,141.0
4,2013-14,24.0,OKC,NBA,PF,17.0,17.0,581.0,87.0,147.0,...,0.765,31.0,85.0,116.0,12.0,11.0,42.0,20.0,54.0,205.0
5,2015-16,26.0,OKC,NBA,PF,18.0,18.0,602.0,85.0,163.0,...,0.750,23.0,90.0,113.0,10.0,14.0,24.0,9.0,51.0,216.0
6,2016-17,27.0,TOR,NBA,PF,10.0,10.0,307.0,60.0,130.0,...,0.846,9.0,56.0,65.0,14.0,4.0,17.0,11.0,37.0,143.0
7,2017-18,28.0,TOR,NBA,PF,10.0,9.0,260.0,30.0,72.0,...,0.818,13.0,46.0,59.0,11.0,1.0,13.0,16.0,21.0,87.0
8,2018-19,29.0,TOR,NBA,C,24.0,0.0,500.0,92.0,193.0,...,0.762,35.0,108.0,143.0,22.0,11.0,23.0,25.0,79.0,225.0
9,2019-20,30.0,TOR,NBA,C,11.0,0.0,251.0,63.0,110.0,...,1.000,17.0,68.0,85.0,13.0,2.0,14.0,12.0,27.0,163.0
10,2020-21,31.0,LAC,NBA,C,2.0,0.0,18.0,3.0,6.0,...,1.000,1.0,3.0,4.0,2.0,1.0,3.0,1.0,1.0,10.0
11,Career,NaN,NaN,NBA,NaN,146.0,102.0,4097.0,650.0,1295.0,...,0.792,275.0,680.0,955.0,109.0,61.0,292.0,139.0,448.0,1599.0
12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,6 seasons,NaN,OKC,NBA,NaN,89.0,83.0,2761.0,402.0,784.0,...,0.768,200.0,399.0,599.0,47.0,42.0,222.0,74.0,283.0,971.0
14,4 seasons,NaN,TOR,NBA,NaN,55.0,19.0,1318.0,245.0,505.0,...,0.824,74.0,278.0,352.0,60.0,18.0,67.0,64.0,164.0,618.0
15,1 season,NaN,LAC,NBA,NaN,2.0,0.0,18.0,3.0,6.0,...,1.000,1.0,3.0,4.0,2.0,1.0,3.0,1.0,1.0,10.0

In [36]:
df2[4].to_csv("players.csv",index=False)

In [37]:
## Data as raw enabled and take from link
df3 = pd.read_csv("https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv")
df3

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [38]:
k = """{
"name" : "Akash",
"phone_no" : "90876",
"company":["Capgemini","EY"]
}
"""

In [39]:
import json

In [40]:
s = json.loads(k)

In [41]:
s

{'name': 'Akash', 'phone_no': '90876', 'company': ['Capgemini', 'EY']}

In [42]:
pd.DataFrame(s)

    name phone_no    company
0  Akash    90876  Capgemini
1  Akash    90876         EY

In [43]:
pd.DataFrame(s,columns=['company'])

     company
0  Capgemini
1         EY

In [44]:
!pip install requests

Requirement already satisfied: requests in c:\users\91706\anaconda3\envs\ai\lib\site-packages (2.25.1)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in c:\users\91706\anaconda3\envs\ai\lib\site-packages (from requests) (1.26.5)
Requirement already satisfied: idna<3,>=2.5 in c:\users\91706\anaconda3\envs\ai\lib\site-packages (from requests) (2.10)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\91706\anaconda3\envs\ai\lib\site-packages (from requests) (2020.12.5)
Requirement already satisfied: chardet<5,>=3.0.2 in c:\users\91706\anaconda3\envs\ai\lib\site-packages (from requests) (4.0.0)

In [45]:
import requests

In [46]:
res = requests.get('https://api.github.com/repos/pandas-dev/pandas/issues')

In [47]:
res

In [48]:
js = res.json()

In [49]:
js[0]

{'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/42102',
 'repository_url': 'https://api.github.com/repos/pandas-dev/pandas',
 'labels_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/42102/labels{/name}',
 'comments_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/42102/comments',
 'events_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/42102/events',
 'html_url': 'https://github.com/pandas-dev/pandas/issues/42102',
 'id': 924727199,
 'node_id': 'MDU6SXNzdWU5MjQ3MjcxOTk=',
 'number': 42102,
 'title': 'Indexing MultiIndex with duplicates return Series instead of raw value ',
 'user': {'login': 'LucasG0',
  'id': 44552904,
  'node_id': 'MDQ6VXNlcjQ0NTUyOTA0',
  'avatar_url': 'https://avatars.githubusercontent.com/u/44552904?v=4',
  'gravatar_id': '',
  'url': 'https://api.github.com/users/LucasG0',
  'html_url': 'https://github.com/LucasG0',
  'followers_url': 'https://api.github.com/users/LucasG0/followers',
  'following_url': 'https://api.github.com/users/LucasG0/following{/other_user}',
  'gists_url': 'https://api.github.com/users/LucasG0/gists{/gist_id}',
  'starred_url': 'https://api.github.com/users/LucasG0/starred{/owner}{/repo}',
  'subscriptions_url': 'https://api.github.com/users/LucasG0/subscriptions',
  'organizations_url': 'https://api.github.com/users/LucasG0/orgs',
  'repos_url': 'https://api.github.com/users/LucasG0/repos',
  'events_url': 'https://api.github.com/users/LucasG0/events{/privacy}',
  'received_events_url': 'https://api.github.com/users/LucasG0/received_events',
  'type': 'User',
  'site_admin': False},
 'labels': [{'id': 76811,
   'node_id': 'MDU6TGFiZWw3NjgxMQ==',
   'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Bug',
   'name': 'Bug',
   'color': 'e10c02',
   'default': False,
   'description': None},
  {'id': 1954720290,
   'node_id': 'MDU6TGFiZWwxOTU0NzIwMjkw',
   'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Needs%20Triage',
   'name': 'Needs Triage',
   'color': '0052cc',
   'default': False,
   'description': 'Issue that has not been reviewed by a pandas team member'}],
 'state': 'open',
 'locked': False,
 'assignee': None,
 'assignees': [],
 'milestone': None,
 'comments': 0,
 'created_at': '2021-06-18T09:36:11Z',
 'updated_at': '2021-06-18T09:36:11Z',
 'closed_at': None,
 'author_association': 'NONE',
 'active_lock_reason': None,
 'body': '- [x] I have checked that this issue has not already been reported.\r\n\r\n- [x] I have confirmed this bug exists on the latest version of pandas.\r\n\r\n- [ ] (optional) I have confirmed this bug exists on the master branch of pandas.\r\n\r\n---\r\n\r\n#### Code Sample, a copy-pastable example\r\n```\r\nsingle_index_no_duplicates = pd.Index([0, 1, 2])\r\nsingle_index_with_duplicates = pd.Index([0, 1, 1])\r\n\r\nmulti_index_no_duplicates = pd.MultiIndex.from_tuples([(0, 0), (0, 1), (1, 0)])\r\nmulti_index_with_duplicates = pd.MultiIndex.from_tuples([(0, 0), (1, 0), (1, 0)])\r\n\r\n>>> pd.Series(range(3), single_index_no_duplicates).loc[0]\r\n0\r\n>>> pd.Series(range(3), single_index_with_duplicates).loc[0]\r\n0\r\n>>> pd.Series(range(3), multi_index_no_duplicates).loc[(0,0)]\r\n0\r\n>>> pd.Series(range(3), multi_index_with_duplicates).loc[(0,0)]\r\n0  0    0\r\ndtype: int64\r\n\r\n```\r\n\r\n#### Problem description\r\n\r\nWhen indexing a unique index value with `.loc` on a `MultiIndex` containing duplicated values,\r\nthe return type is a `Series `while it is a raw value for single `Index`. \r\n\r\n#### Expected Output\r\n\r\nI think we should expect a raw value to keep consistent with `Index` behavior.\r\n\r\n```\r\n>>> pd.Series(range(3), multi_index_with_duplicates).loc[(0,0)]\r\n0\r\n```\r\n\r\n#### Output of ``pd.show_versions()``\r\n\r\n<details>\r\n\r\nINSTALLED VERSIONS\r\n------------------\r\ncommit           : 2cb96529396d93b46abab7bbc73a208e708c642e\r\npython           : 3.8.5.final.0\r\npython-bits      : 64\r\nOS               : Linux\r\nOS-release       : 5.8.0-55-generic\r\nVersion          : #62~20.04.1-Ubuntu SMP Wed Jun 2 08:55:04 UTC 2021\r\nmachine          : x86_64\r\nprocessor        : x86_64\r\nbyteorder        : little\r\nLC_ALL           : None\r\nLANG             : fr_FR.UTF-8\r\nLOCALE           : fr_FR.UTF-8\r\n\r\npandas           : 1.2.4\r\nnumpy            : 1.20.3\r\npytz             : 2019.3\r\ndateutil         : 2.7.3\r\npip              : 20.0.2\r\nsetuptools       : 45.2.0\r\nCython           : None\r\npytest           : 6.2.4\r\nhypothesis       : None\r\nsphinx           : None\r\nblosc            : None\r\nfeather          : None\r\nxlsxwriter       : None\r\nlxml.etree       : None\r\nhtml5lib         : 1.1\r\npymysql          : None\r\npsycopg2         : None\r\njinja2           : None\r\nIPython          : None\r\npandas_datareader: None\r\nbs4              : None\r\nbottleneck       : None\r\nfsspec           : None\r\nfastparquet      : None\r\ngcsfs            : None\r\nmatplotlib       : None\r\nnumexpr          : None\r\nodfpy            : None\r\nopenpyxl         : None\r\npandas_gbq       : None\r\npyarrow          : None\r\npyxlsb           : None\r\ns3fs             : None\r\nscipy            : None\r\nsqlalchemy       : None\r\ntables           : None\r\ntabulate         : None\r\nxarray           : None\r\nxlrd             : None\r\nxlwt             : None\r\nnumba            : None\r\n\r\n</details>\r\n',
 'performed_via_github_app': None}

In [50]:
## to access from this dictionary
js[0]['title']

'Indexing MultiIndex with duplicates return Series instead of raw value '

In [51]:
for i in js:
    print(i['title'])

Indexing MultiIndex with duplicates return Series instead of raw value
BUG: `Styler.hide_columns()` does not hide index name row
REF: use only inherit_names in CategoricalIndex
BUG: Adding Series to empty DataFrame can reset dtype to float64
CLN: use fused type for lib.has_infs
REGR: Subclassing `Styler` and addressing `from_custom_template`
[WIP] BUG: fix `Series.argsort`
REGR: undocumented astype("category").astype(str) type inconsistency between pandas 1.1 & 1.2
BUG: groupby any/all raising with pd.NA object data
PERF/CLN: to_csv
When change default dtype for empty Series?
CI: disable auto-cancel for master branch
BUG: error writing sparse DataFrame to HDF
BUG: pd.to_datetime(infer_datetime_format=True) drops timezone
DOC: How to use storage_option param here to integrate with GCP bucket?
BUG: rolling std can't handle mixture of (relatively) big and small numbers
BUG: avoid unnecessary casting in CategoricalIndex.reindex
Allow passing custom sentinel into MultiIndex.format
BUG: pd.Series.argsort misaligned index
BUG: IndexError when slicing a series, if a level of MultiIndex contains only NaN values
ENH: Implement skiptrailingspace parameter for the read_table function
BUG: `Styler` subclassing and `from_custom_template` no longer working
BUG: hash_pandas_object ignores optional arguments when the input is a DataFrame.
TYP: Type hints & assert statements
PERF: groupsort_indexer contiguity
CI: fsspec 2021.6.0 failures
BUG: passing str to GroupBy.apply
Fix module name for _LoadSparseFrame
BUG: groupby with dropna=False and 'unique' aggregate creates duplicated index
BUG: `Styler.apply` consistently manages Series return objects aligning labels.

In [52]:
pd.DataFrame(js,columns=['url','title'])

,url,title
0,https://api.github.com/repos/pandas-dev/pandas...,Indexing MultiIndex with duplicates return Ser...
1,https://api.github.com/repos/pandas-dev/pandas...,BUG: `Styler.hide_columns()` does not hide ind...
2,https://api.github.com/repos/pandas-dev/pandas...,REF: use only inherit_names in CategoricalIndex
3,https://api.github.com/repos/pandas-dev/pandas...,BUG: Adding Series to empty DataFrame can rese...
4,https://api.github.com/repos/pandas-dev/pandas...,CLN: use fused type for lib.has_infs
5,https://api.github.com/repos/pandas-dev/pandas...,REGR: Subclassing `Styler` and addressing `fro...
6,https://api.github.com/repos/pandas-dev/pandas...,[WIP] BUG: fix `Series.argsort`
7,https://api.github.com/repos/pandas-dev/pandas...,"REGR: undocumented astype(""category"").astype(s..."
8,https://api.github.com/repos/pandas-dev/pandas...,BUG: groupby any/all raising with pd.NA object...
9,https://api.github.com/repos/pandas-dev/pandas...,PERF/CLN: to_csv
10,https://api.github.com/repos/pandas-dev/pandas...,When change default dtype for empty Series?
11,https://api.github.com/repos/pandas-dev/pandas...,CI: disable auto-cancel for master branch
12,https://api.github.com/repos/pandas-dev/pandas...,BUG: error writing sparse DataFrame to HDF
13,https://api.github.com/repos/pandas-dev/pandas...,BUG: pd.to_datetime(infer_datetime_format=True...
14,https://api.github.com/repos/pandas-dev/pandas...,DOC: How to use storage_option param here to i...
15,https://api.github.com/repos/pandas-dev/pandas...,BUG: rolling std can't handle mixture of (rela...
16,https://api.github.com/repos/pandas-dev/pandas...,BUG: avoid unnecessary casting in CategoricalI...
17,https://api.github.com/repos/pandas-dev/pandas...,Allow passing custom sentinel into MultiIndex....
18,https://api.github.com/repos/pandas-dev/pandas...,BUG: pd.Series.argsort misaligned index
19,https://api.github.com/repos/pandas-dev/pandas...,"BUG: IndexError when slicing a series, if a le..."
20,https://api.github.com/repos/pandas-dev/pandas...,ENH: Implement skiptrailingspace parameter for...
21,https://api.github.com/repos/pandas-dev/pandas...,BUG: `Styler` subclassing and `from_custom_tem...
22,https://api.github.com/repos/pandas-dev/pandas...,BUG: hash_pandas_object ignores optional argum...
23,https://api.github.com/repos/pandas-dev/pandas...,TYP: Type hints & assert statements
24,https://api.github.com/repos/pandas-dev/pandas...,PERF: groupsort_indexer contiguity
25,https://api.github.com/repos/pandas-dev/pandas...,CI: fsspec 2021.6.0 failures
26,https://api.github.com/repos/pandas-dev/pandas...,BUG: passing str to GroupBy.apply
27,https://api.github.com/repos/pandas-dev/pandas...,Fix module name for _LoadSparseFrame
28,https://api.github.com/repos/pandas-dev/pandas...,BUG: groupby with dropna=False and 'unique' ag...
29,https://api.github.com/repos/pandas-dev/pandas...,BUG: `Styler.apply` consistently manages Serie...

In [67]:
df4 = pd.DataFrame(js)
df4

,url,repository_url,labels_url,comments_url,events_url,html_url,id,node_id,number,title,...,milestone,comments,created_at,updated_at,closed_at,author_association,active_lock_reason,body,performed_via_github_app,pull_request
0,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/issues/42102,924727199,MDU6SXNzdWU5MjQ3MjcxOTk=,42102,Indexing MultiIndex with duplicates return Ser...,...,None,0,2021-06-18T09:36:11Z,2021-06-18T09:36:11Z,None,NONE,None,- [x] I have checked that this issue has not a...,None,NaN
1,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/issues/42101,924653848,MDU6SXNzdWU5MjQ2NTM4NDg=,42101,BUG: `Styler.hide_columns()` does not hide ind...,...,{'url': 'https://api.github.com/repos/pandas-d...,0,2021-06-18T08:06:17Z,2021-06-18T08:06:34Z,None,CONTRIBUTOR,None,Whilst `Styler.hide_index()` hides column head...,None,NaN
2,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/pull/42100,924492994,MDExOlB1bGxSZXF1ZXN0NjczMTI1MjQz,42100,REF: use only inherit_names in CategoricalIndex,...,None,0,2021-06-18T02:55:34Z,2021-06-18T02:55:34Z,None,MEMBER,None,- [ ] closes #xxxx\r\n- [ ] tests added / pass...,None,{'url': 'https://api.github.com/repos/pandas-d...
3,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/issues/42099,924489175,MDU6SXNzdWU5MjQ0ODkxNzU=,42099,BUG: Adding Series to empty DataFrame can rese...,...,None,0,2021-06-18T02:44:56Z,2021-06-18T02:44:56Z,None,CONTRIBUTOR,None,- [x] I have checked that this issue has not a...,None,NaN
4,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/pull/42095,924423382,MDExOlB1bGxSZXF1ZXN0NjczMDY3MjQ3,42095,CLN: use fused type for lib.has_infs,...,None,0,2021-06-17T23:53:58Z,2021-06-18T05:01:36Z,None,MEMBER,None,\r\n,None,{'url': 'https://api.github.com/repos/pandas-d...
5,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/pull/42091,924339951,MDExOlB1bGxSZXF1ZXN0NjcyOTk0MDE2,42091,REGR: Subclassing `Styler` and addressing `fro...,...,None,0,2021-06-17T21:15:30Z,2021-06-18T05:18:23Z,None,CONTRIBUTOR,None,- [x] closes #42053\r\n\r\nMore info there - n...,None,{'url': 'https://api.github.com/repos/pandas-d...
6,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/pull/42090,924320847,MDExOlB1bGxSZXF1ZXN0NjcyOTc3NDM4,42090,[WIP] BUG: fix `Series.argsort`,...,None,0,2021-06-17T20:46:07Z,2021-06-18T09:08:50Z,None,CONTRIBUTOR,None,- [x] closes #42056\r\n\r\n### No Nulls:\r\n\r...,None,{'url': 'https://api.github.com/repos/pandas-d...
7,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/pull/42087,924257194,MDExOlB1bGxSZXF1ZXN0NjcyOTIxNDE2,42087,"REGR: undocumented astype(""category"").astype(s...",...,{'url': 'https://api.github.com/repos/pandas-d...,0,2021-06-17T19:21:57Z,2021-06-18T08:32:04Z,None,MEMBER,None,- [ ] closes #41797\r\n- [ ] tests added / pas...,None,{'url': 'https://api.github.com/repos/pandas-d...
8,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/pull/42085,924218159,MDExOlB1bGxSZXF1ZXN0NjcyODg3OTEy,42085,BUG: groupby any/all raising with pd.NA object...,...,{'url': 'https://api.github.com/repos/pandas-d...,0,2021-06-17T18:29:40Z,2021-06-18T05:06:03Z,None,MEMBER,None,- [x] closes #37501\r\n- [x] tests added / pas...,None,{'url': 'https://api.github.com/repos/pandas-d...
9,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/pull/42084,924199896,MDExOlB1bGxSZXF1ZXN0NjcyODcyMzI4,42084,PERF/CLN: to_csv,...,None,0,2021-06-17T18:05:55Z,2021-06-17T20:10:55Z,None,MEMBER,None,- [ ] xref #41468\r\n- [ ] tests added / passe...,None,{'url': 'https://api.github.com/repos/pandas-d...
10,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/issues/42078,924103162,MDU6SXNzdWU5MjQxMDMxNjI=,42078,When change default dtype for empty Series?,...,None,1,2021-06-17T16:10:36Z,2021-06-17T19:31:29Z,None,NONE,None,Hello! \r\nI see ``<stdin>:1: DeprecationWarni...,None,NaN
11,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/issues/42076,923949616,MDU6SXNzdWU5MjM5NDk2MTY=,42076,CI: disable auto-cancel for master branch,...,None,0,2021-06-17T13:49:20Z,2021-06-17T13:53:53Z,None,MEMBER,None,#41962 enabled auto-cancel for GitHub Actions ...,None,NaN
12,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/issues/42070,923841994,MDU6SXNzdWU5MjM4NDE5OTQ=,42070,BUG: error writing sparse DataFrame to HDF,...,None,0,2021-06-17T12:00:44Z,2021-06-17T12:00:57Z,None,NONE,None,- [x] I have checked that this issue has not a...,None,NaN
13,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/pull/42068,923795038,MDExOlB1bGxSZXF1ZXN0NjcyNTE5NzIw,42068,BUG: pd.to_datetime(infer_datetime_format=True...,...,None,0,2021-06-17T11:07:52Z,2021-06-18T01:52:09Z,None,NONE,None,- [x] closes #41047\r\n- [x] tests added / pas...,None,{'url': 'https://api.github.com/repos/pandas-d...
14,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/issues/42066,923718271,MDU6SXNzdWU5MjM3MTgyNzE=,42066,DOC: How to use storage_option param here to i...,...,{'url': 'https://api.github.com/repos/pandas-d...,0,2021-06-17T09:46:51Z,2021-06-17T10:28:09Z,None,NONE,None,#### Location of the documentation\r\n\r\nhttp...,None,NaN
15,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/issues/42064,923497965,MDU6SXNzdWU5MjM0OTc5NjU=,42064,BUG: rolling std can't handle mixture of (rela...,...,None,4,2021-06-17T06:12:34Z,2021-06-17T17:02:23Z,None,NONE,None,- [x] I have checked that this issue has not a...,None,NaN
16,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/pull/42063,923284191,MDExOlB1bGxSZXF1ZXN0NjcyMDY1NjMz,42063,BUG: avoid unnecessary casting in CategoricalI...,...,None,2,2021-06-17T01:10:38Z,2021-06-18T02:04:27Z,None,MEMBER,None,Doesn't appear to be anything user-facing. Th...,None,{'url': 'https://api.github.com/repos/pandas-d...
17,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/pull/42061,923202362,MDExOlB1bGxSZXF1ZXN0NjcxOTkxNTA5,42061,Allow passing custom sentinel into MultiIndex....,...,None,3,2021-06-16T23:13:37Z,2021-06-17T18:59:55Z,None,NONE,None,Commit b0468aa45f3 seems to have unintentional...,None,{'url': 'https://api.github.com/repos/pandas-d...
18,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/issues/42056,922981573,MDU6SXNzdWU5MjI5ODE1NzM=,42056,BUG: pd.Series.argsort misaligned index,...,None,1,2021-06-16T19:00:59Z,2021-06-17T08:24:43Z,None,NONE,None,- [X] I have checked that this issue has not a...,None,NaN
19,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/issues/42055,922682512,MDU6SXNzdWU5MjI2ODI1MTI=,42055,"BUG: IndexError when slicing a series, if a le...",...,None,2,2021-06-16T14:22:36Z,2021-06-16T21:27:08Z,None,NONE,None,- [x] I have checked that this issue has not a...,None,NaN
20,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/issues/42054,922632256,MDU6SXNzdWU5MjI2MzIyNTY=,42054,ENH: Implement skiptrailingspace parameter for...,...,None,3,2021-06-16T13:43:33Z,2021-06-17T04:12:29Z,None,CONTRIBUTOR,None,#### Is your feature request related to a prob...,None,NaN
21,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/issues/42053,922620241,MDU6SXNzdWU5MjI2MjAyNDE=,42053,BUG: `Styler` subclassing and `from_custom_tem...,...,None,0,2021-06-16T13:33:28Z,2021-06-17T21:11:11Z,None,CONTRIBUTOR,None,PR #40312 introduced jinja2 template inheritan...,None,NaN
22,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/pull/42049,922082430,MDExOlB1bGxSZXF1ZXN0NjcwOTk5MjYx,42049,BUG: hash_pandas_object ignores optional argum...,...,{'url': 'https://api.github.com/repos/pandas-d...,2,2021-06-16T04:36:32Z,2021-06-18T07:33:11Z,None,NONE,None,- [x] closes #41404\r\n- [x] tests added / pas...,None,{'url': 'https://api.github.com/repos/pandas-d...
23,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/pull/42044,921953068,MDExOlB1bGxSZXF1ZXN0NjcwODg1MTcw,42044,TYP: Type hints & assert statements,...,None,4,2021-06-16T00:53:34Z,2021-06-16T12:39:29Z,None,NONE,None,This PR addresses two concerns of best practic...,None,{'url': 'https://api.github.com/repos/pandas-d...
24,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/pull/42031,921831711,MDExOlB1bGxSZXF1ZXN0NjcwNzc1OTc5,42031,PERF: groupsort_indexer contiguity,...,{'url': 'https://api.github.com/repos/pandas-d...,0,2021-06-15T21:50:27Z,2021-06-16T15:09:06Z,None,MEMBER,None,Some low-hanging fruit\r\n```\r\nIn [1]: impor...,None,{'url': 'https://api.github.com/repos/pandas-d...
25,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/issues/42026,921773567,MDU6SXNzdWU5MjE3NzM1Njc=,42026,CI: fsspec 2021.6.0 failures,...,{'url': 'https://api.github.com/repos/pandas-d...,1,2021-06-15T20:29:35Z,2021-06-16T10:17:07Z,None,MEMBER,None,`pandas/tests/io/test_fsspec.py::test_read_csv...,None,NaN
26,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/pull/42021,921632519,MDExOlB1bGxSZXF1ZXN0NjcwNjA3NzE0,42021,BUG: passing str to GroupBy.apply,...,None,0,2021-06-15T17:25:53Z,2021-06-16T18:27:47Z,None,MEMBER,None,- [ ] closes #xxxx\r\n- [x] tests added / pass...,None,{'url': 'https://api.github.com/repos/pandas-d...
27,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/pull/42020,921571575,MDExOlB1bGxSZXF1ZXN0NjcwNTU1NDA4,42020,Fix module name for _LoadSparseFrame,...,None,7,2021-06-15T16:13:50Z,2021-06-15T23:18:28Z,None,NONE,None,,None,{'url': 'https://api.github.com/repos/pandas-d...
28,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/issues/42016,921278453,MDU6SXNzdWU5MjEyNzg0NTM=,42016,BUG: groupby with dropna=False and 'unique' ag...,...,None,2,2021-06-15T11:06:26Z,2021-06-15T15:17:35Z,None,NONE,None,- [x] I have checked that this issue has not a...,None,NaN
29,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/pull/42014,921086510,MDExOlB1bGxSZXF1ZXN0NjcwMTQxMDIz,42014,BUG: `Styler.apply` consistently manages Serie...,...,None,0,2021-06-15T07:22:49Z,2021-06-15T11:30:06Z,None,CONTRIBUTOR,None,- [x] closes #13657 \r\n\r\nThis issue is due ...,None,{'url': 'https://api.github.com/repos/pandas-d...

In [55]:
df4.to_csv('json_dump.csv')

In [57]:
k = js[0]['user']
k

{'login': 'LucasG0',
 'id': 44552904,
 'node_id': 'MDQ6VXNlcjQ0NTUyOTA0',
 'avatar_url': 'https://avatars.githubusercontent.com/u/44552904?v=4',
 'gravatar_id': '',
 'url': 'https://api.github.com/users/LucasG0',
 'html_url': 'https://github.com/LucasG0',
 'followers_url': 'https://api.github.com/users/LucasG0/followers',
 'following_url': 'https://api.github.com/users/LucasG0/following{/other_user}',
 'gists_url': 'https://api.github.com/users/LucasG0/gists{/gist_id}',
 'starred_url': 'https://api.github.com/users/LucasG0/starred{/owner}{/repo}',
 'subscriptions_url': 'https://api.github.com/users/LucasG0/subscriptions',
 'organizations_url': 'https://api.github.com/users/LucasG0/orgs',
 'repos_url': 'https://api.github.com/users/LucasG0/repos',
 'events_url': 'https://api.github.com/users/LucasG0/events{/privacy}',
 'received_events_url': 'https://api.github.com/users/LucasG0/received_events',
 'type': 'User',
 'site_admin': False}

In [70]:
t = []
for i in k:
    t.append(i)
print(t)

['login', 'id', 'node_id', 'avatar_url', 'gravatar_id', 'url', 'html_url', 'followers_url', 'following_url', 'gists_url', 'starred_url', 'subscriptions_url', 'organizations_url', 'repos_url', 'events_url', 'received_events_url', 'type', 'site_admin']

In [75]:
f = pd.DataFrame(k,columns=t,index=[0])
f

,login,id,node_id,avatar_url,gravatar_id,url,html_url,followers_url,following_url,gists_url,starred_url,subscriptions_url,organizations_url,repos_url,events_url,received_events_url,type,site_admin
0,LucasG0,44552904,MDQ6VXNlcjQ0NTUyOTA0,https://avatars.githubusercontent.com/u/445529...,,https://api.github.com/users/LucasG0,https://github.com/LucasG0,https://api.github.com/users/LucasG0/followers,https://api.github.com/users/LucasG0/following...,https://api.github.com/users/LucasG0/gists{/gi...,https://api.github.com/users/LucasG0/starred{/...,https://api.github.com/users/LucasG0/subscript...,https://api.github.com/users/LucasG0/orgs,https://api.github.com/users/LucasG0/repos,https://api.github.com/users/LucasG0/events{/p...,https://api.github.com/users/LucasG0/received_...,User,False

In [76]:
lst = []
for i in range(len(js)):
    lst.append(js[i]['user'])

In [77]:
lst

[{'login': 'LucasG0',
  'id': 44552904,
  'node_id': 'MDQ6VXNlcjQ0NTUyOTA0',
  'avatar_url': 'https://avatars.githubusercontent.com/u/44552904?v=4',
  'gravatar_id': '',
  'url': 'https://api.github.com/users/LucasG0',
  'html_url': 'https://github.com/LucasG0',
  'followers_url': 'https://api.github.com/users/LucasG0/followers',
  'following_url': 'https://api.github.com/users/LucasG0/following{/other_user}',
  'gists_url': 'https://api.github.com/users/LucasG0/gists{/gist_id}',
  'starred_url': 'https://api.github.com/users/LucasG0/starred{/owner}{/repo}',
  'subscriptions_url': 'https://api.github.com/users/LucasG0/subscriptions',
  'organizations_url': 'https://api.github.com/users/LucasG0/orgs',
  'repos_url': 'https://api.github.com/users/LucasG0/repos',
  'events_url': 'https://api.github.com/users/LucasG0/events{/privacy}',
  'received_events_url': 'https://api.github.com/users/LucasG0/received_events',
  'type': 'User',
  'site_admin': False},
 {'login': 'attack68',
  'id': 24256554,
  'node_id': 'MDQ6VXNlcjI0MjU2NTU0',
  'avatar_url': 'https://avatars.githubusercontent.com/u/24256554?v=4',
  'gravatar_id': '',
  'url': 'https://api.github.com/users/attack68',
  'html_url': 'https://github.com/attack68',
  'followers_url': 'https://api.github.com/users/attack68/followers',
  'following_url': 'https://api.github.com/users/attack68/following{/other_user}',
  'gists_url': 'https://api.github.com/users/attack68/gists{/gist_id}',
  'starred_url': 'https://api.github.com/users/attack68/starred{/owner}{/repo}',
  'subscriptions_url': 'https://api.github.com/users/attack68/subscriptions',
  'organizations_url': 'https://api.github.com/users/attack68/orgs',
  'repos_url': 'https://api.github.com/users/attack68/repos',
  'events_url': 'https://api.github.com/users/attack68/events{/privacy}',
  'received_events_url': 'https://api.github.com/users/attack68/received_events',
  'type': 'User',
  'site_admin': False},
 {'login': 'jbrockmendel',
  'id': 8078968,
  'node_id': 'MDQ6VXNlcjgwNzg5Njg=',
  'avatar_url': 'https://avatars.githubusercontent.com/u/8078968?v=4',
  'gravatar_id': '',
  'url': 'https://api.github.com/users/jbrockmendel',
  'html_url': 'https://github.com/jbrockmendel',
  'followers_url': 'https://api.github.com/users/jbrockmendel/followers',
  'following_url': 'https://api.github.com/users/jbrockmendel/following{/other_user}',
  'gists_url': 'https://api.github.com/users/jbrockmendel/gists{/gist_id}',
  'starred_url': 'https://api.github.com/users/jbrockmendel/starred{/owner}{/repo}',
  'subscriptions_url': 'https://api.github.com/users/jbrockmendel/subscriptions',
  'organizations_url': 'https://api.github.com/users/jbrockmendel/orgs',
  'repos_url': 'https://api.github.com/users/jbrockmendel/repos',
  'events_url': 'https://api.github.com/users/jbrockmendel/events{/privacy}',
  'received_events_url': 'https://api.github.com/users/jbrockmendel/received_events',
  'type': 'User',
  'site_admin': False},
 {'login': 'JBGreisman',
  'id': 6944142,
  'node_id': 'MDQ6VXNlcjY5NDQxNDI=',
  'avatar_url': 'https://avatars.githubusercontent.com/u/6944142?v=4',
  'gravatar_id': '',
  'url': 'https://api.github.com/users/JBGreisman',
  'html_url': 'https://github.com/JBGreisman',
  'followers_url': 'https://api.github.com/users/JBGreisman/followers',
  'following_url': 'https://api.github.com/users/JBGreisman/following{/other_user}',
  'gists_url': 'https://api.github.com/users/JBGreisman/gists{/gist_id}',
  'starred_url': 'https://api.github.com/users/JBGreisman/starred{/owner}{/repo}',
  'subscriptions_url': 'https://api.github.com/users/JBGreisman/subscriptions',
  'organizations_url': 'https://api.github.com/users/JBGreisman/orgs',
  'repos_url': 'https://api.github.com/users/JBGreisman/repos',
  'events_url': 'https://api.github.com/users/JBGreisman/events{/privacy}',
  'received_events_url': 'https://api.github.com/users/JBGreisman/received_events',
  'type': 'User',
  'site_admin': False},
 {'login': 'mzeitlin11',
  'id': 37011898,
  'node_id': 'MDQ6VXNlcjM3MDExODk4',
  'avatar_url': 'https://avatars.githubusercontent.com/u/37011898?v=4',
  'gravatar_id': '',
  'url': 'https://api.github.com/users/mzeitlin11',
  'html_url': 'https://github.com/mzeitlin11',
  'followers_url': 'https://api.github.com/users/mzeitlin11/followers',
  'following_url': 'https://api.github.com/users/mzeitlin11/following{/other_user}',
  'gists_url': 'https://api.github.com/users/mzeitlin11/gists{/gist_id}',
  'starred_url': 'https://api.github.com/users/mzeitlin11/starred{/owner}{/repo}',
  'subscriptions_url': 'https://api.github.com/users/mzeitlin11/subscriptions',
  'organizations_url': 'https://api.github.com/users/mzeitlin11/orgs',
  'repos_url': 'https://api.github.com/users/mzeitlin11/repos',
  'events_url': 'https://api.github.com/users/mzeitlin11/events{/privacy}',
  'received_events_url': 'https://api.github.com/users/mzeitlin11/received_events',
  'type': 'User',
  'site_admin': False},
 {'login': 'attack68',
  'id': 24256554,
  'node_id': 'MDQ6VXNlcjI0MjU2NTU0',
  'avatar_url': 'https://avatars.githubusercontent.com/u/24256554?v=4',
  'gravatar_id': '',
  'url': 'https://api.github.com/users/attack68',
  'html_url': 'https://github.com/attack68',
  'followers_url': 'https://api.github.com/users/attack68/followers',
  'following_url': 'https://api.github.com/users/attack68/following{/other_user}',
  'gists_url': 'https://api.github.com/users/attack68/gists{/gist_id}',
  'starred_url': 'https://api.github.com/users/attack68/starred{/owner}{/repo}',
  'subscriptions_url': 'https://api.github.com/users/attack68/subscriptions',
  'organizations_url': 'https://api.github.com/users/attack68/orgs',
  'repos_url': 'https://api.github.com/users/attack68/repos',
  'events_url': 'https://api.github.com/users/attack68/events{/privacy}',
  'received_events_url': 'https://api.github.com/users/attack68/received_events',
  'type': 'User',
  'site_admin': False},
 {'login': 'attack68',
  'id': 24256554,
  'node_id': 'MDQ6VXNlcjI0MjU2NTU0',
  'avatar_url': 'https://avatars.githubusercontent.com/u/24256554?v=4',
  'gravatar_id': '',
  'url': 'https://api.github.com/users/attack68',
  'html_url': 'https://github.com/attack68',
  'followers_url': 'https://api.github.com/users/attack68/followers',
  'following_url': 'https://api.github.com/users/attack68/following{/other_user}',
  'gists_url': 'https://api.github.com/users/attack68/gists{/gist_id}',
  'starred_url': 'https://api.github.com/users/attack68/starred{/owner}{/repo}',
  'subscriptions_url': 'https://api.github.com/users/attack68/subscriptions',
  'organizations_url': 'https://api.github.com/users/attack68/orgs',
  'repos_url': 'https://api.github.com/users/attack68/repos',
  'events_url': 'https://api.github.com/users/attack68/events{/privacy}',
  'received_events_url': 'https://api.github.com/users/attack68/received_events',
  'type': 'User',
  'site_admin': False},
 {'login': 'simonjayhawkins',
  'id': 13159005,
  'node_id': 'MDQ6VXNlcjEzMTU5MDA1',
  'avatar_url': 'https://avatars.githubusercontent.com/u/13159005?v=4',
  'gravatar_id': '',
  'url': 'https://api.github.com/users/simonjayhawkins',
  'html_url': 'https://github.com/simonjayhawkins',
  'followers_url': 'https://api.github.com/users/simonjayhawkins/followers',
  'following_url': 'https://api.github.com/users/simonjayhawkins/following{/other_user}',
  'gists_url': 'https://api.github.com/users/simonjayhawkins/gists{/gist_id}',
  'starred_url': 'https://api.github.com/users/simonjayhawkins/starred{/owner}{/repo}',
  'subscriptions_url': 'https://api.github.com/users/simonjayhawkins/subscriptions',
  'organizations_url': 'https://api.github.com/users/simonjayhawkins/orgs',
  'repos_url': 'https://api.github.com/users/simonjayhawkins/repos',
  'events_url': 'https://api.github.com/users/simonjayhawkins/events{/privacy}',
  'received_events_url': 'https://api.github.com/users/simonjayhawkins/received_events',
  'type': 'User',
  'site_admin': False},
 {'login': 'mzeitlin11',
  'id': 37011898,
  'node_id': 'MDQ6VXNlcjM3MDExODk4',
  'avatar_url': 'https://avatars.githubusercontent.com/u/37011898?v=4',
  'gravatar_id': '',
  'url': 'https://api.github.com/users/mzeitlin11',
  'html_url': 'https://github.com/mzeitlin11',
  'followers_url': 'https://api.github.com/users/mzeitlin11/followers',
  'following_url': 'https://api.github.com/users/mzeitlin11/following{/other_user}',
  'gists_url': 'https://api.github.com/users/mzeitlin11/gists{/gist_id}',
  'starred_url': 'https://api.github.com/users/mzeitlin11/starred{/owner}{/repo}',
  'subscriptions_url': 'https://api.github.com/users/mzeitlin11/subscriptions',
  'organizations_url': 'https://api.github.com/users/mzeitlin11/orgs',
  'repos_url': 'https://api.github.com/users/mzeitlin11/repos',
  'events_url': 'https://api.github.com/users/mzeitlin11/events{/privacy}',
  'received_events_url': 'https://api.github.com/users/mzeitlin11/received_events',
  'type': 'User',
  'site_admin': False},
 {'login': 'lithomas1',
  'id': 47963215,
  'node_id': 'MDQ6VXNlcjQ3OTYzMjE1',
  'avatar_url': 'https://avatars.githubusercontent.com/u/47963215?v=4',
  'gravatar_id': '',
  'url': 'https://api.github.com/users/lithomas1',
  'html_url': 'https://github.com/lithomas1',
  'followers_url': 'https://api.github.com/users/lithomas1/followers',
  'following_url': 'https://api.github.com/users/lithomas1/following{/other_user}',
  'gists_url': 'https://api.github.com/users/lithomas1/gists{/gist_id}',
  'starred_url': 'https://api.github.com/users/lithomas1/starred{/owner}{/repo}',
  'subscriptions_url': 'https://api.github.com/users/lithomas1/subscriptions',
  'organizations_url': 'https://api.github.com/users/lithomas1/orgs',
  'repos_url': 'https://api.github.com/users/lithomas1/repos',
  'events_url': 'https://api.github.com/users/lithomas1/events{/privacy}',
  'received_events_url': 'https://api.github.com/users/lithomas1/received_events',
  'type': 'User',
  'site_admin': False},
 {'login': 'Rubtsowa',
  'id': 36762665,
  'node_id': 'MDQ6VXNlcjM2NzYyNjY1',
  'avatar_url': 'https://avatars.githubusercontent.com/u/36762665?v=4',
  'gravatar_id': '',
  'url': 'https://api.github.com/users/Rubtsowa',
  'html_url': 'https://github.com/Rubtsowa',
  'followers_url': 'https://api.github.com/users/Rubtsowa/followers',
  'following_url': 'https://api.github.com/users/Rubtsowa/following{/other_user}',
  'gists_url': 'https://api.github.com/users/Rubtsowa/gists{/gist_id}',
  'starred_url': 'https://api.github.com/users/Rubtsowa/starred{/owner}{/repo}',
  'subscriptions_url': 'https://api.github.com/users/Rubtsowa/subscriptions',
  'organizations_url': 'https://api.github.com/users/Rubtsowa/orgs',
  'repos_url': 'https://api.github.com/users/Rubtsowa/repos',
  'events_url': 'https://api.github.com/users/Rubtsowa/events{/privacy}',
  'received_events_url': 'https://api.github.com/users/Rubtsowa/received_events',
  'type': 'User',
  'site_admin': False},
 {'login': 'fangchenli',
  'id': 7614606,
  'node_id': 'MDQ6VXNlcjc2MTQ2MDY=',
  'avatar_url': 'https://avatars.githubusercontent.com/u/7614606?v=4',
  'gravatar_id': '',
  'url': 'https://api.github.com/users/fangchenli',
  'html_url': 'https://github.com/fangchenli',
  'followers_url': 'https://api.github.com/users/fangchenli/followers',
  'following_url': 'https://api.github.com/users/fangchenli/following{/other_user}',
  'gists_url': 'https://api.github.com/users/fangchenli/gists{/gist_id}',
  'starred_url': 'https://api.github.com/users/fangchenli/starred{/owner}{/repo}',
  'subscriptions_url': 'https://api.github.com/users/fangchenli/subscriptions',
  'organizations_url': 'https://api.github.com/users/fangchenli/orgs',
  'repos_url': 'https://api.github.com/users/fangchenli/repos',
  'events_url': 'https://api.github.com/users/fangchenli/events{/privacy}',
  'received_events_url': 'https://api.github.com/users/fangchenli/received_events',
  'type': 'User',
  'site_admin': False},
 {'login': 'raphaelquast',
  'id': 22773387,
  'node_id': 'MDQ6VXNlcjIyNzczMzg3',
  'avatar_url': 'https://avatars.githubusercontent.com/u/22773387?v=4',
  'gravatar_id': '',
  'url': 'https://api.github.com/users/raphaelquast',
  'html_url': 'https://github.com/raphaelquast',
  'followers_url': 'https://api.github.com/users/raphaelquast/followers',
  'following_url': 'https://api.github.com/users/raphaelquast/following{/other_user}',
  'gists_url': 'https://api.github.com/users/raphaelquast/gists{/gist_id}',
  'starred_url': 'https://api.github.com/users/raphaelquast/starred{/owner}{/repo}',
  'subscriptions_url': 'https://api.github.com/users/raphaelquast/subscriptions',
  'organizations_url': 'https://api.github.com/users/raphaelquast/orgs',
  'repos_url': 'https://api.github.com/users/raphaelquast/repos',
  'events_url': 'https://api.github.com/users/raphaelquast/events{/privacy}',
  'received_events_url': 'https://api.github.com/users/raphaelquast/received_events',
  'type': 'User',
  'site_admin': False},
 {'login': 'i-aki-y',
  'id': 9190086,
  'node_id': 'MDQ6VXNlcjkxOTAwODY=',
  'avatar_url': 'https://avatars.githubusercontent.com/u/9190086?v=4',
  'gravatar_id': '',
  'url': 'https://api.github.com/users/i-aki-y',
  'html_url': 'https://github.com/i-aki-y',
  'followers_url': 'https://api.github.com/users/i-aki-y/followers',
  'following_url': 'https://api.github.com/users/i-aki-y/following{/other_user}',
  'gists_url': 'https://api.github.com/users/i-aki-y/gists{/gist_id}',
  'starred_url': 'https://api.github.com/users/i-aki-y/starred{/owner}{/repo}',
  'subscriptions_url': 'https://api.github.com/users/i-aki-y/subscriptions',
  'organizations_url': 'https://api.github.com/users/i-aki-y/orgs',
  'repos_url': 'https://api.github.com/users/i-aki-y/repos',
  'events_url': 'https://api.github.com/users/i-aki-y/events{/privacy}',
  'received_events_url': 'https://api.github.com/users/i-aki-y/received_events',
  'type': 'User',
  'site_admin': False},
 {'login': 'KayvanShah1',
  'id': 59110083,
  'node_id': 'MDQ6VXNlcjU5MTEwMDgz',
  'avatar_url': 'https://avatars.githubusercontent.com/u/59110083?v=4',
  'gravatar_id': '',
  'url': 'https://api.github.com/users/KayvanShah1',
  'html_url': 'https://github.com/KayvanShah1',
  'followers_url': 'https://api.github.com/users/KayvanShah1/followers',
  'following_url': 'https://api.github.com/users/KayvanShah1/following{/other_user}',
  'gists_url': 'https://api.github.com/users/KayvanShah1/gists{/gist_id}',
  'starred_url': 'https://api.github.com/users/KayvanShah1/starred{/owner}{/repo}',
  'subscriptions_url': 'https://api.github.com/users/KayvanShah1/subscriptions',
  'organizations_url': 'https://api.github.com/users/KayvanShah1/orgs',
  'repos_url': 'https://api.github.com/users/KayvanShah1/repos',
  'events_url': 'https://api.github.com/users/KayvanShah1/events{/privacy}',
  'received_events_url': 'https://api.github.com/users/KayvanShah1/received_events',
  'type': 'User',
  'site_admin': False},
 {'login': 'auderson',
  'id': 48577571,
  'node_id': 'MDQ6VXNlcjQ4NTc3NTcx',
  'avatar_url': 'https://avatars.githubusercontent.com/u/48577571?v=4',
  'gravatar_id': '',
  'url': 'https://api.github.com/users/auderson',
  'html_url': 'https://github.com/auderson',
  'followers_url': 'https://api.github.com/users/auderson/followers',
  'following_url': 'https://api.github.com/users/auderson/following{/other_user}',
  'gists_url': 'https://api.github.com/users/auderson/gists{/gist_id}',
  'starred_url': 'https://api.github.com/users/auderson/starred{/owner}{/repo}',
  'subscriptions_url': 'https://api.github.com/users/auderson/subscriptions',
  'organizations_url': 'https://api.github.com/users/auderson/orgs',
  'repos_url': 'https://api.github.com/users/auderson/repos',
  'events_url': 'https://api.github.com/users/auderson/events{/privacy}',
  'received_events_url': 'https://api.github.com/users/auderson/received_events',
  'type': 'User',
  'site_admin': False},
 {'login': 'jbrockmendel',
  'id': 8078968,
  'node_id': 'MDQ6VXNlcjgwNzg5Njg=',
  'avatar_url': 'https://avatars.githubusercontent.com/u/8078968?v=4',
  'gravatar_id': '',
  'url': 'https://api.github.com/users/jbrockmendel',
  'html_url': 'https://github.com/jbrockmendel',
  'followers_url': 'https://api.github.com/users/jbrockmendel/followers',
  'following_url': 'https://api.github.com/users/jbrockmendel/following{/other_user}',
  'gists_url': 'https://api.github.com/users/jbrockmendel/gists{/gist_id}',
  'starred_url': 'https://api.github.com/users/jbrockmendel/starred{/owner}{/repo}',
  'subscriptions_url': 'https://api.github.com/users/jbrockmendel/subscriptions',
  'organizations_url': 'https://api.github.com/users/jbrockmendel/orgs',
  'repos_url': 'https://api.github.com/users/jbrockmendel/repos',
  'events_url': 'https://api.github.com/users/jbrockmendel/events{/privacy}',
  'received_events_url': 'https://api.github.com/users/jbrockmendel/received_events',
  'type': 'User',
  'site_admin': False},
 {'login': 'eltoder',
  'id': 4088528,
  'node_id': 'MDQ6VXNlcjQwODg1Mjg=',
  'avatar_url': 'https://avatars.githubusercontent.com/u/4088528?v=4',
  'gravatar_id': '',
  'url': 'https://api.github.com/users/eltoder',
  'html_url': 'https://github.com/eltoder',
  'followers_url': 'https://api.github.com/users/eltoder/followers',
  'following_url': 'https://api.github.com/users/eltoder/following{/other_user}',
  'gists_url': 'https://api.github.com/users/eltoder/gists{/gist_id}',
  'starred_url': 'https://api.github.com/users/eltoder/starred{/owner}{/repo}',
  'subscriptions_url': 'https://api.github.com/users/eltoder/subscriptions',
  'organizations_url': 'https://api.github.com/users/eltoder/orgs',
  'repos_url': 'https://api.github.com/users/eltoder/repos',
  'events_url': 'https://api.github.com/users/eltoder/events{/privacy}',
  'received_events_url': 'https://api.github.com/users/eltoder/received_events',
  'type': 'User',
  'site_admin': False},
 {'login': 'cericson',
  'id': 6691014,
  'node_id': 'MDQ6VXNlcjY2OTEwMTQ=',
  'avatar_url': 'https://avatars.githubusercontent.com/u/6691014?v=4',
  'gravatar_id': '',
  'url': 'https://api.github.com/users/cericson',
  'html_url': 'https://github.com/cericson',
  'followers_url': 'https://api.github.com/users/cericson/followers',
  'following_url': 'https://api.github.com/users/cericson/following{/other_user}',
  'gists_url': 'https://api.github.com/users/cericson/gists{/gist_id}',
  'starred_url': 'https://api.github.com/users/cericson/starred{/owner}{/repo}',
  'subscriptions_url': 'https://api.github.com/users/cericson/subscriptions',
  'organizations_url': 'https://api.github.com/users/cericson/orgs',
  'repos_url': 'https://api.github.com/users/cericson/repos',
  'events_url': 'https://api.github.com/users/cericson/events{/privacy}',
  'received_events_url': 'https://api.github.com/users/cericson/received_events',
  'type': 'User',
  'site_admin': False},
 {'login': 'sziem',
  'id': 15675934,
  'node_id': 'MDQ6VXNlcjE1Njc1OTM0',
  'avatar_url': 'https://avatars.githubusercontent.com/u/15675934?v=4',
  'gravatar_id': '',
  'url': 'https://api.github.com/users/sziem',
  'html_url': 'https://github.com/sziem',
  'followers_url': 'https://api.github.com/users/sziem/followers',
  'following_url': 'https://api.github.com/users/sziem/following{/other_user}',
  'gists_url': 'https://api.github.com/users/sziem/gists{/gist_id}',
  'starred_url': 'https://api.github.com/users/sziem/starred{/owner}{/repo}',
  'subscriptions_url': 'https://api.github.com/users/sziem/subscriptions',
  'organizations_url': 'https://api.github.com/users/sziem/orgs',
  'repos_url': 'https://api.github.com/users/sziem/repos',
  'events_url': 'https://api.github.com/users/sziem/events{/privacy}',
  'received_events_url': 'https://api.github.com/users/sziem/received_events',
  'type': 'User',
  'site_admin': False},
 {'login': 'owenlamont',
  'id': 12672027,
  'node_id': 'MDQ6VXNlcjEyNjcyMDI3',

In [78]:
pd.DataFrame(lst)

,login,id,node_id,avatar_url,gravatar_id,url,html_url,followers_url,following_url,gists_url,starred_url,subscriptions_url,organizations_url,repos_url,events_url,received_events_url,type,site_admin
0,LucasG0,44552904,MDQ6VXNlcjQ0NTUyOTA0,https://avatars.githubusercontent.com/u/445529...,,https://api.github.com/users/LucasG0,https://github.com/LucasG0,https://api.github.com/users/LucasG0/followers,https://api.github.com/users/LucasG0/following...,https://api.github.com/users/LucasG0/gists{/gi...,https://api.github.com/users/LucasG0/starred{/...,https://api.github.com/users/LucasG0/subscript...,https://api.github.com/users/LucasG0/orgs,https://api.github.com/users/LucasG0/repos,https://api.github.com/users/LucasG0/events{/p...,https://api.github.com/users/LucasG0/received_...,User,False
1,attack68,24256554,MDQ6VXNlcjI0MjU2NTU0,https://avatars.githubusercontent.com/u/242565...,,https://api.github.com/users/attack68,https://github.com/attack68,https://api.github.com/users/attack68/followers,https://api.github.com/users/attack68/followin...,https://api.github.com/users/attack68/gists{/g...,https://api.github.com/users/attack68/starred{...,https://api.github.com/users/attack68/subscrip...,https://api.github.com/users/attack68/orgs,https://api.github.com/users/attack68/repos,https://api.github.com/users/attack68/events{/...,https://api.github.com/users/attack68/received...,User,False
2,jbrockmendel,8078968,MDQ6VXNlcjgwNzg5Njg=,https://avatars.githubusercontent.com/u/807896...,,https://api.github.com/users/jbrockmendel,https://github.com/jbrockmendel,https://api.github.com/users/jbrockmendel/foll...,https://api.github.com/users/jbrockmendel/foll...,https://api.github.com/users/jbrockmendel/gist...,https://api.github.com/users/jbrockmendel/star...,https://api.github.com/users/jbrockmendel/subs...,https://api.github.com/users/jbrockmendel/orgs,https://api.github.com/users/jbrockmendel/repos,https://api.github.com/users/jbrockmendel/even...,https://api.github.com/users/jbrockmendel/rece...,User,False
3,JBGreisman,6944142,MDQ6VXNlcjY5NDQxNDI=,https://avatars.githubusercontent.com/u/694414...,,https://api.github.com/users/JBGreisman,https://github.com/JBGreisman,https://api.github.com/users/JBGreisman/followers,https://api.github.com/users/JBGreisman/follow...,https://api.github.com/users/JBGreisman/gists{...,https://api.github.com/users/JBGreisman/starre...,https://api.github.com/users/JBGreisman/subscr...,https://api.github.com/users/JBGreisman/orgs,https://api.github.com/users/JBGreisman/repos,https://api.github.com/users/JBGreisman/events...,https://api.github.com/users/JBGreisman/receiv...,User,False
4,mzeitlin11,37011898,MDQ6VXNlcjM3MDExODk4,https://avatars.githubusercontent.com/u/370118...,,https://api.github.com/users/mzeitlin11,https://github.com/mzeitlin11,https://api.github.com/users/mzeitlin11/followers,https://api.github.com/users/mzeitlin11/follow...,https://api.github.com/users/mzeitlin11/gists{...,https://api.github.com/users/mzeitlin11/starre...,https://api.github.com/users/mzeitlin11/subscr...,https://api.github.com/users/mzeitlin11/orgs,https://api.github.com/users/mzeitlin11/repos,https://api.github.com/users/mzeitlin11/events...,https://api.github.com/users/mzeitlin11/receiv...,User,False
5,attack68,24256554,MDQ6VXNlcjI0MjU2NTU0,https://avatars.githubusercontent.com/u/242565...,,https://api.github.com/users/attack68,https://github.com/attack68,https://api.github.com/users/attack68/followers,https://api.github.com/users/attack68/followin...,https://api.github.com/users/attack68/gists{/g...,https://api.github.com/users/attack68/starred{...,https://api.github.com/users/attack68/subscrip...,https://api.github.com/users/attack68/orgs,https://api.github.com/users/attack68/repos,https://api.github.com/users/attack68/events{/...,https://api.github.com/users/attack68/received...,User,False
6,attack68,24256554,MDQ6VXNlcjI0MjU2NTU0,https://avatars.githubusercontent.com/u/242565...,,https://api.github.com/users/attack68,https://github.com/attack68,https://api.github.com/users/attack68/followers,https://api.github.com/users/attack68/followin...,https://api.github.com/users/attack68/gists{/g...,https://api.github.com/users/attack68/starred{...,https://api.github.com/users/attack68/subscrip...,https://api.github.com/users/attack68/orgs,https://api.github.com/users/attack68/repos,https://api.github.com/users/attack68/events{/...,https://api.github.com/users/attack68/received...,User,False
7,simonjayhawkins,13159005,MDQ6VXNlcjEzMTU5MDA1,https://avatars.githubusercontent.com/u/131590...,,https://api.github.com/users/simonjayhawkins,https://github.com/simonjayhawkins,https://api.github.com/users/simonjayhawkins/f...,https://api.github.com/users/simonjayhawkins/f...,https://api.github.com/users/simonjayhawkins/g...,https://api.github.com/users/simonjayhawkins/s...,https://api.github.com/users/simonjayhawkins/s...,https://api.github.com/users/simonjayhawkins/orgs,https://api.github.com/users/simonjayhawkins/r...,https://api.github.com/users/simonjayhawkins/e...,https://api.github.com/users/simonjayhawkins/r...,User,False
8,mzeitlin11,37011898,MDQ6VXNlcjM3MDExODk4,https://avatars.githubusercontent.com/u/370118...,,https://api.github.com/users/mzeitlin11,https://github.com/mzeitlin11,https://api.github.com/users/mzeitlin11/followers,https://api.github.com/users/mzeitlin11/follow...,https://api.github.com/users/mzeitlin11/gists{...,https://api.github.com/users/mzeitlin11/starre...,https://api.github.com/users/mzeitlin11/subscr...,https://api.github.com/users/mzeitlin11/orgs,https://api.github.com/users/mzeitlin11/repos,https://api.github.com/users/mzeitlin11/events...,https://api.github.com/users/mzeitlin11/receiv...,User,False
9,lithomas1,47963215,MDQ6VXNlcjQ3OTYzMjE1,https://avatars.githubusercontent.com/u/479632...,,https://api.github.com/users/lithomas1,https://github.com/lithomas1,https://api.github.com/users/lithomas1/followers,https://api.github.com/users/lithomas1/followi...,https://api.github.com/users/lithomas1/gists{/...,https://api.github.com/users/lithomas1/starred...,https://api.github.com/users/lithomas1/subscri...,https://api.github.com/users/lithomas1/orgs,https://api.github.com/users/lithomas1/repos,https://api.github.com/users/lithomas1/events{...,https://api.github.com/users/lithomas1/receive...,User,False
10,Rubtsowa,36762665,MDQ6VXNlcjM2NzYyNjY1,https://avatars.githubusercontent.com/u/367626...,,https://api.github.com/users/Rubtsowa,https://github.com/Rubtsowa,https://api.github.com/users/Rubtsowa/followers,https://api.github.com/users/Rubtsowa/followin...,https://api.github.com/users/Rubtsowa/gists{/g...,https://api.github.com/users/Rubtsowa/starred{...,https://api.github.com/users/Rubtsowa/subscrip...,https://api.github.com/users/Rubtsowa/orgs,https://api.github.com/users/Rubtsowa/repos,https://api.github.com/users/Rubtsowa/events{/...,https://api.github.com/users/Rubtsowa/received...,User,False
11,fangchenli,7614606,MDQ6VXNlcjc2MTQ2MDY=,https://avatars.githubusercontent.com/u/761460...,,https://api.github.com/users/fangchenli,https://github.com/fangchenli,https://api.github.com/users/fangchenli/followers,https://api.github.com/users/fangchenli/follow...,https://api.github.com/users/fangchenli/gists{...,https://api.github.com/users/fangchenli/starre...,https://api.github.com/users/fangchenli/subscr...,https://api.github.com/users/fangchenli/orgs,https://api.github.com/users/fangchenli/repos,https://api.github.com/users/fangchenli/events...,https://api.github.com/users/fangchenli/receiv...,User,False
12,raphaelquast,22773387,MDQ6VXNlcjIyNzczMzg3,https://avatars.githubusercontent.com/u/227733...,,https://api.github.com/users/raphaelquast,https://github.com/raphaelquast,https://api.github.com/users/raphaelquast/foll...,https://api.github.com/users/raphaelquast/foll...,https://api.github.com/users/raphaelquast/gist...,https://api.github.com/users/raphaelquast/star...,https://api.github.com/users/raphaelquast/subs...,https://api.github.com/users/raphaelquast/orgs,https://api.github.com/users/raphaelquast/repos,https://api.github.com/users/raphaelquast/even...,https://api.github.com/users/raphaelquast/rece...,User,False
13,i-aki-y,9190086,MDQ6VXNlcjkxOTAwODY=,https://avatars.githubusercontent.com/u/919008...,,https://api.github.com/users/i-aki-y,https://github.com/i-aki-y,https://api.github.com/users/i-aki-y/followers,https://api.github.com/users/i-aki-y/following...,https://api.github.com/users/i-aki-y/gists{/gi...,https://api.github.com/users/i-aki-y/starred{/...,https://api.github.com/users/i-aki-y/subscript...,https://api.github.com/users/i-aki-y/orgs,https://api.github.com/users/i-aki-y/repos,https://api.github.com/users/i-aki-y/events{/p...,https://api.github.com/users/i-aki-y/received_...,User,False
14,KayvanShah1,59110083,MDQ6VXNlcjU5MTEwMDgz,https://avatars.githubusercontent.com/u/591100...,,https://api.github.com/users/KayvanShah1,https://github.com/KayvanShah1,https://api.github.com/users/KayvanShah1/follo...,https://api.github.com/users/KayvanShah1/follo...,https://api.github.com/users/KayvanShah1/gists...,https://api.github.com/users/KayvanShah1/starr...,https://api.github.com/users/KayvanShah1/subsc...,https://api.github.com/users/KayvanShah1/orgs,https://api.github.com/users/KayvanShah1/repos,https://api.github.com/users/KayvanShah1/event...,https://api.github.com/users/KayvanShah1/recei...,User,False
15,auderson,48577571,MDQ6VXNlcjQ4NTc3NTcx,https://avatars.githubusercontent.com/u/485775...,,https://api.github.com/users/auderson,https://github.com/auderson,https://api.github.com/users/auderson/followers,https://api.github.com/users/auderson/followin...,https://api.github.com/users/auderson/gists{/g...,https://api.github.com/users/auderson/starred{...,https://api.github.com/users/auderson/subscrip...,https://api.github.com/users/auderson/orgs,https://api.github.com/users/auderson/repos,https://api.github.com/users/auderson/events{/...,https://api.github.com/users/auderson/received...,User,False
16,jbrockmendel,8078968,MDQ6VXNlcjgwNzg5Njg=,https://avatars.githubusercontent.com/u/807896...,,https://api.github.com/users/jbrockmendel,https://github.com/jbrockmendel,https://api.github.com/users/jbrockmendel/foll...,https://api.github.com/users/jbrockmendel/foll...,https://api.github.com/users/jbrockmendel/gist...,https://api.github.com/users/jbrockmendel/star...,https://api.github.com/users/jbrockmendel/subs...,https://api.github.com/users/jbrockmendel/orgs,https://api.github.com/users/jbrockmendel/repos,https://api.github.com/users/jbrockmendel/even...,https://api.github.com/users/jbrockmendel/rece...,User,False
17,eltoder,4088528,MDQ6VXNlcjQwODg1Mjg=,https://avatars.githubusercontent.com/u/408852...,,https://api.github.com/users/eltoder,https://github.com/eltoder,https://api.github.com/users/eltoder/followers,https://api.github.com/users/eltoder/following...,https://api.github.com/users/eltoder/gists{/gi...,https://api.github.com/users/eltoder/starred{/...,https://api.github.com/users/eltoder/subscript...,https://api.github.com/users/eltoder/orgs,https://api.github.com/users/eltoder/repos,https://api.github.com/users/eltoder/events{/p...,https://api.github.com/users/eltoder/received_...,User,False
18,cericson,6691014,MDQ6VXNlcjY2OTEwMTQ=,https://avatars.githubusercontent.com/u/669101...,,https://api.github.com/users/cericson,https://github.com/cericson,https://api.github.com/users/cericson/followers,https://api.github.com/users/cericson/followin...,https://api.github.com/users/cericson/gists{/g...,https://api.github.com/users/cericson/starred{...,https://api.github.com/users/cericson/subscrip...,https://api.github.com/users/cericson/orgs,https://api.github.com/users/cericson/repos,https://api.github.com/users/cericson/events{/...,https://api.github.com/users/cericson/received...,User,False
19,sziem,15675934,MDQ6VXNlcjE1Njc1OTM0,https://avatars.githubusercontent.com/u/156759...,,https://api.github.com/users/sziem,https://github.com/sziem,https://api.github.com/users/sziem/followers,https://api.github.com/users/sziem/following{/...,https://api.github.com/users/sziem/gists{/gist...,https://api.github.com/users/sziem/starred{/ow...,https://api.github.com/users/sziem/subscriptions,https://api.github.com/users/sziem/orgs,https://api.github.com/users/sziem/repos,https://api.github.com/users/sziem/events{/pri...,https://api.github.com/users/sziem/received_ev...,User,False
20,owenlamont,12672027,MDQ6VXNlcjEyNjcyMDI3,https://avatars.githubusercontent.com/u/126720...,,https://api.github.com/users/owenlamont,https://github.com/owenlamont,https://api.github.com/users/owenlamont/followers,https://api.github.com/users/owenlamont/follow...,https://api.github.com/users/owenlamont/gists{...,https://api.github.com/users/owenlamont/starre...,https://api.github.com/users/owenlamont/subscr...,https://api.github.com/users/owenlamont/orgs,https://api.github.com/users/owenlamont/repos,https://api.github.com/users/owenlamont/events...,https://api.github.com/users/owenlamont/receiv...,User,False
21,attack68,24256554,MDQ6VXNlcjI0MjU2NTU0,https://avatars.githubusercontent.com/u/242565...,,https://api.github.com/users/attack68,https://github.com/attack68,https://api.github.com/users/attack68/followers,https://api.github.com/users/attack68/followin...,https://api.github.com/users/attack68/gists{/g...,https://api.github.com/users/attack68/starred{...,https://api.github.com/users/attack68/subscrip...,https://api.github.com/users/attack68/orgs,https://api.github.com/users/attack68/repos,https://api.github.com/users/attack68/events{/...,https://api.github.com/users/attack68/received...,User,False
22,i-aki-y,9190086,MDQ6VXNlcjkxOTAwODY=,https://avatars.githubusercontent.com/u/919008...,,https://api.github.com/users/i-aki-y,https://github.com/i-aki-y,https://api.github.com/users/i-aki-y/followers,https://api.github.com/users/i-aki-y/following...,https://api.github.com/users/i-aki-y/gists{/gi...,https://api.github.com/users/i-aki-y/starred{/...,https://api.github.com/users/i-aki-y/subscript...,https://api.github.com/users/i-aki-y/orgs,https://api.github.com/users/i-aki-y/repos,https://api.github.com/users/i-aki-y/events{/p...,https://api.github.com/users/i-aki-y/received_...,User,False
23,rgkimball,7003930,MDQ6VXNlcjcwMDM5MzA=,https://avatars.githubusercontent.com/u/700393...,,https://api.github.com/users/rgkimball,https://github.com/rgkimball,https://api.github.com/users/rgkimball/followers,https://api.github.com/users/rgkimball/followi...,https://api.github.com/users/rgkimball/gists{/...,https://api.github.com/users/rgkimball/starred...,https://api.github.com/users/rgkimball/subscri...,https://api.github.com/users/rgkimball/orgs,https://api.github.com/users/rgkimball/repos,https://api.github.com/users/rgkimball/events{...,https://api.github.com/users/rgkimball/receive...,User,False
24,mzeitlin11,37011898,MDQ6VXNlcjM3MDExODk4,https://avatars.githubusercontent.com/u/370118...,,https://api.github.com/users/mzeitlin11,https://github.com/mzeitlin11,https://api.github.com/users/mzeitlin11/followers,https://api.github.com/users/mzeitlin11/follow...,https://api.github.com/users/mzeitlin11/gists{...,https://api.github.com/users/mzeitlin11/starre...,https://api.github.com/users/mzeitlin11/subscr...,https://api.github.com/users/mzeitlin11/orgs,https://api.github.com/users/mzeitlin11/repos,https://api.github.com/users/mzeitlin11/events...,https://api.github.com/users/mzeitlin11/receiv...,User,False
25,mzeitlin11,37011898,MDQ6VXNlcjM3MDExODk4,https://avatars.githubusercontent.com/u/370118...,,https://api.github.com/users/mzeitlin11,https://github.com/mzeitlin11,https://api.github.com/users/mzeitlin11/followers,https://api.github.com/users/mzeitlin11/follow...,https://api.github.com/users/mzeitlin11/gists{...,https://api.github.com/users/mzeitlin11/starre...,https://api.github.com/users/mzeitlin11/subscr...,https://api.github.com/users/mzeitlin11/orgs,https://api.github.com/users/mzeitlin11/repos,https://api.github.com/users/mzeitlin11/events...,https://api.github.com/users/mzeitlin11/receiv...,User,False
26,jbrockmendel,8078968,MDQ6VXNlcjgwNzg5Njg=,https://avatars.githubusercontent.com/u/807896...,,https://api.github.com/users/jbrockmendel,https://github.com/jbrockmendel,https://api.github.com/users/jbrockmendel/foll...,https://api.github.com/users/jbrockmendel/foll...,https://api.github.com/users/jbrockmendel/gist...,https://api.github.com/users/jbrockmendel/star...,https://api.github.com/users/jbrockmendel/subs...,https://api.github.com/users/jbrockmendel/orgs,https://api.github.com/users/jbrockmendel/repos,https://api.github.com/users/jbrockmendel/even...,https://api.github.com/users/jbrockmendel/rece...,User,False
27,eltoder,4088528,MDQ6VXNlcjQwODg1Mjg=,https://avatars.githubusercontent.com/u/408852...,,https://api.github.com/users/eltoder,https://github.com/eltoder,https://api.github.com/users/eltoder/followers,https://api.github.com/users/eltoder/following...,https://api.github.com/users/eltoder/gists{/gi...,https://api.github.com/users/eltoder/starred{/...,https://api.github.com/users/eltoder/subscript...,https://api.github.com/users/eltoder/orgs,https://api.github.com/users/eltoder/repos,https://api.github.com/users/eltoder/events{/p...,https://api.github.com/users/eltoder/received_...,User,False
28,mhabets,2016449,MDQ6VXNlcjIwMTY0NDk=,https://avatars.githubusercontent.com/u/201644...,,https://api.github.com/users/mhabets,https://github.com/mhabets,https://api.github.com/users/mhabets/followers,https://api.github.com/users/mhabets/following...,https://api.github.com/users/mhabets/gists{/gi...,https://api.github.com/users/mhabets/starred{/...,https://api.github.com/users/mhabets/subscript...,https://api.github.com/users/mhabets/orgs,https://api.github.com/users/mhabets/repos,https://api.github.com/users/mhabets/events{/p...,https://api.github.com/users/mhabets/received_...,User,False
29,attack68,24256554,MDQ6VXNlcjI0MjU2NTU0,https://avatars.githubusercontent.com/u/242565...,,https://api.github.com/users/attack68,https://github.com/attack68,https://api.github.com/users/attack68/followers,https://api.github.com/users/attack68/followin...,https://api.github.com/users/attack68/gists{/g...,https://api.github.com/users/attack68/starred{...,https://api.github.com/users/attack68/subscrip...,https://api.github.com/users/attack68/orgs,https://api.github.com/users/attack68/repos,https://api.github.com/users/attack68/events{/...,https://api.github.com/users/attack68/received...,User,False

In [79]:
## Different Approach
json_data = pd.read_json('https://api.github.com/repos/pandas-dev/pandas/issues')
data = pd.DataFrame.from_records(json_data['user'])
data.head(6)

,login,id,node_id,avatar_url,gravatar_id,url,html_url,followers_url,following_url,gists_url,starred_url,subscriptions_url,organizations_url,repos_url,events_url,received_events_url,type,site_admin
0,LucasG0,44552904,MDQ6VXNlcjQ0NTUyOTA0,https://avatars.githubusercontent.com/u/445529...,,https://api.github.com/users/LucasG0,https://github.com/LucasG0,https://api.github.com/users/LucasG0/followers,https://api.github.com/users/LucasG0/following...,https://api.github.com/users/LucasG0/gists{/gi...,https://api.github.com/users/LucasG0/starred{/...,https://api.github.com/users/LucasG0/subscript...,https://api.github.com/users/LucasG0/orgs,https://api.github.com/users/LucasG0/repos,https://api.github.com/users/LucasG0/events{/p...,https://api.github.com/users/LucasG0/received_...,User,False
1,attack68,24256554,MDQ6VXNlcjI0MjU2NTU0,https://avatars.githubusercontent.com/u/242565...,,https://api.github.com/users/attack68,https://github.com/attack68,https://api.github.com/users/attack68/followers,https://api.github.com/users/attack68/followin...,https://api.github.com/users/attack68/gists{/g...,https://api.github.com/users/attack68/starred{...,https://api.github.com/users/attack68/subscrip...,https://api.github.com/users/attack68/orgs,https://api.github.com/users/attack68/repos,https://api.github.com/users/attack68/events{/...,https://api.github.com/users/attack68/received...,User,False
2,jbrockmendel,8078968,MDQ6VXNlcjgwNzg5Njg=,https://avatars.githubusercontent.com/u/807896...,,https://api.github.com/users/jbrockmendel,https://github.com/jbrockmendel,https://api.github.com/users/jbrockmendel/foll...,https://api.github.com/users/jbrockmendel/foll...,https://api.github.com/users/jbrockmendel/gist...,https://api.github.com/users/jbrockmendel/star...,https://api.github.com/users/jbrockmendel/subs...,https://api.github.com/users/jbrockmendel/orgs,https://api.github.com/users/jbrockmendel/repos,https://api.github.com/users/jbrockmendel/even...,https://api.github.com/users/jbrockmendel/rece...,User,False
3,JBGreisman,6944142,MDQ6VXNlcjY5NDQxNDI=,https://avatars.githubusercontent.com/u/694414...,,https://api.github.com/users/JBGreisman,https://github.com/JBGreisman,https://api.github.com/users/JBGreisman/followers,https://api.github.com/users/JBGreisman/follow...,https://api.github.com/users/JBGreisman/gists{...,https://api.github.com/users/JBGreisman/starre...,https://api.github.com/users/JBGreisman/subscr...,https://api.github.com/users/JBGreisman/orgs,https://api.github.com/users/JBGreisman/repos,https://api.github.com/users/JBGreisman/events...,https://api.github.com/users/JBGreisman/receiv...,User,False
4,mzeitlin11,37011898,MDQ6VXNlcjM3MDExODk4,https://avatars.githubusercontent.com/u/370118...,,https://api.github.com/users/mzeitlin11,https://github.com/mzeitlin11,https://api.github.com/users/mzeitlin11/followers,https://api.github.com/users/mzeitlin11/follow...,https://api.github.com/users/mzeitlin11/gists{...,https://api.github.com/users/mzeitlin11/starre...,https://api.github.com/users/mzeitlin11/subscr...,https://api.github.com/users/mzeitlin11/orgs,https://api.github.com/users/mzeitlin11/repos,https://api.github.com/users/mzeitlin11/events...,https://api.github.com/users/mzeitlin11/receiv...,User,False
5,attack68,24256554,MDQ6VXNlcjI0MjU2NTU0,https://avatars.githubusercontent.com/u/242565...,,https://api.github.com/users/attack68,https://github.com/attack68,https://api.github.com/users/attack68/followers,https://api.github.com/users/attack68/followin...,https://api.github.com/users/attack68/gists{/g...,https://api.github.com/users/attack68/starred{...,https://api.github.com/users/attack68/subscrip...,https://api.github.com/users/attack68/orgs,https://api.github.com/users/attack68/repos,https://api.github.com/users/attack68/events{/...,https://api.github.com/users/attack68/received...,User,False

In [81]:
ds = pd.read_csv("players.csv")
ds

,Season,Age,Team,Lg,Pos,G,MP,PER,TS%,3PAr,...,Unnamed: 19,OWS,DWS,WS,WS/48,Unnamed: 24,OBPM,DBPM,BPM,VORP
0,2009-10,20.0,OKC,NBA,PF,73.0,1323.0,15.2,0.562,0.005,...,NaN,1.3,2.4,3.7,0.134,NaN,-2.4,0.9,-1.5,0.2
1,2010-11,21.0,OKC,NBA,PF,82.0,2216.0,17.7,0.579,0.002,...,NaN,4.3,3.2,7.6,0.164,NaN,-0.2,0.7,0.5,1.4
2,2011-12,22.0,OKC,NBA,PF,66.0,1792.0,19.0,0.556,0.006,...,NaN,3.0,3.2,6.2,0.167,NaN,0.1,2.3,2.3,1.9
3,2012-13,23.0,OKC,NBA,PF,80.0,2486.0,19.4,0.612,0.073,...,NaN,5.3,4.1,9.4,0.181,NaN,0.9,0.7,1.5,2.2
4,2013-14,24.0,OKC,NBA,PF,81.0,2666.0,19.6,0.576,0.061,...,NaN,5.2,4.4,9.6,0.173,NaN,1.1,0.6,1.7,2.5
5,2014-15,25.0,OKC,NBA,PF,64.0,2116.0,16.6,0.549,0.261,...,NaN,2.9,2.7,5.6,0.127,NaN,0.5,0.4,0.9,1.6
6,2015-16,26.0,OKC,NBA,PF,78.0,2500.0,13.9,0.533,0.212,...,NaN,2.5,3.0,5.5,0.105,NaN,-0.6,0.0,-0.6,0.8
7,2016-17,27.0,TOT,NBA,PF,79.0,2422.0,16.4,0.566,0.323,...,NaN,2.5,2.6,5.1,0.101,NaN,0.4,-0.3,0.1,1.2
8,2016-17,27.0,ORL,NBA,PF,56.0,1710.0,17.5,0.569,0.304,...,NaN,2.1,1.7,3.8,0.108,NaN,0.9,-0.2,0.7,1.2
9,2016-17,27.0,TOR,NBA,PF,23.0,712.0,13.8,0.556,0.369,...,NaN,0.4,0.8,1.3,0.085,NaN,-0.8,-0.6,-1.5,0.1
10,2017-18,28.0,TOR,NBA,PF,76.0,2093.0,14.7,0.574,0.379,...,NaN,2.1,3.0,5.1,0.117,NaN,-0.1,0.0,-0.1,1.0
11,2018-19,29.0,TOR,NBA,C,74.0,2010.0,18.7,0.582,0.193,...,NaN,2.8,3.3,6.1,0.146,NaN,0.2,0.1,0.2,1.2
12,2019-20,30.0,TOR,NBA,C,55.0,1485.0,17.3,0.583,0.272,...,NaN,1.2,2.7,3.9,0.126,NaN,0.1,0.0,0.1,0.8
13,2020-21,31.0,LAC,NBA,C,41.0,955.0,18.2,0.585,0.315,...,NaN,1.7,1.3,3.0,0.150,NaN,1.3,-0.5,0.8,0.7
14,Career,NaN,NaN,NBA,NaN,849.0,24064.0,17.2,0.571,0.186,...,NaN,34.9,35.9,70.8,0.141,NaN,0.2,0.4,0.6,15.5
15,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,7 seasons,NaN,OKC,NBA,NaN,524.0,15099.0,17.5,0.567,0.105,...,NaN,24.5,23.1,47.6,0.151,NaN,0.1,0.7,0.8,10.7
17,4 seasons,NaN,TOR,NBA,NaN,228.0,6300.0,16.5,0.577,0.288,...,NaN,6.6,9.8,16.4,0.125,NaN,-0.1,0.0,-0.1,3.1
18,1 season,NaN,ORL,NBA,NaN,56.0,1710.0,17.5,0.569,0.304,...,NaN,2.1,1.7,3.8,0.108,NaN,0.9,-0.2,0.7,1.2
19,1 season,NaN,LAC,NBA,NaN,41.0,955.0,18.2,0.585,0.315,...,NaN,1.7,1.3,3.0,0.150,NaN,1.3,-0.5,0.8,0.7

In [82]:
ds.to_pickle("my_pickel")

In [84]:
!pip install tables

Collecting tables
  Downloading tables-3.6.1-2-cp37-cp37m-win_amd64.whl (3.1 MB)
Collecting numexpr>=2.6.2
  Downloading numexpr-2.7.3-cp37-cp37m-win_amd64.whl (93 kB)
Requirement already satisfied: numpy>=1.9.3 in c:\users\91706\anaconda3\envs\ai\lib\site-packages (from tables) (1.20.3)
Installing collected packages: numexpr, tables
Successfully installed numexpr-2.7.3 tables-3.6.1

In [85]:
h5_Data=pd.HDFStore('players_hdstorefile.h5')

In [86]:
h5_Data['obj1'] = ds

C:\Users\91706\anaconda3\envs\AI\lib\site-packages\IPython\core\interactiveshell.py:3441: PerformanceWarning:
your performance may suffer as PyTables will pickle object types that it cannot
map directly to c-types [inferred_type->mixed,key->block1_values] [items->Index(['Season', 'Team', 'Lg', 'Pos'], dtype='object')]

  exec(code_obj, self.user_global_ns, self.user_ns)

In [87]:
h5_Data['obj1']

,Season,Age,Team,Lg,Pos,G,MP,PER,TS%,3PAr,...,Unnamed: 19,OWS,DWS,WS,WS/48,Unnamed: 24,OBPM,DBPM,BPM,VORP
0,2009-10,20.0,OKC,NBA,PF,73.0,1323.0,15.2,0.562,0.005,...,NaN,1.3,2.4,3.7,0.134,NaN,-2.4,0.9,-1.5,0.2
1,2010-11,21.0,OKC,NBA,PF,82.0,2216.0,17.7,0.579,0.002,...,NaN,4.3,3.2,7.6,0.164,NaN,-0.2,0.7,0.5,1.4
2,2011-12,22.0,OKC,NBA,PF,66.0,1792.0,19.0,0.556,0.006,...,NaN,3.0,3.2,6.2,0.167,NaN,0.1,2.3,2.3,1.9
3,2012-13,23.0,OKC,NBA,PF,80.0,2486.0,19.4,0.612,0.073,...,NaN,5.3,4.1,9.4,0.181,NaN,0.9,0.7,1.5,2.2
4,2013-14,24.0,OKC,NBA,PF,81.0,2666.0,19.6,0.576,0.061,...,NaN,5.2,4.4,9.6,0.173,NaN,1.1,0.6,1.7,2.5
5,2014-15,25.0,OKC,NBA,PF,64.0,2116.0,16.6,0.549,0.261,...,NaN,2.9,2.7,5.6,0.127,NaN,0.5,0.4,0.9,1.6
6,2015-16,26.0,OKC,NBA,PF,78.0,2500.0,13.9,0.533,0.212,...,NaN,2.5,3.0,5.5,0.105,NaN,-0.6,0.0,-0.6,0.8
7,2016-17,27.0,TOT,NBA,PF,79.0,2422.0,16.4,0.566,0.323,...,NaN,2.5,2.6,5.1,0.101,NaN,0.4,-0.3,0.1,1.2
8,2016-17,27.0,ORL,NBA,PF,56.0,1710.0,17.5,0.569,0.304,...,NaN,2.1,1.7,3.8,0.108,NaN,0.9,-0.2,0.7,1.2
9,2016-17,27.0,TOR,NBA,PF,23.0,712.0,13.8,0.556,0.369,...,NaN,0.4,0.8,1.3,0.085,NaN,-0.8,-0.6,-1.5,0.1
10,2017-18,28.0,TOR,NBA,PF,76.0,2093.0,14.7,0.574,0.379,...,NaN,2.1,3.0,5.1,0.117,NaN,-0.1,0.0,-0.1,1.0
11,2018-19,29.0,TOR,NBA,C,74.0,2010.0,18.7,0.582,0.193,...,NaN,2.8,3.3,6.1,0.146,NaN,0.2,0.1,0.2,1.2
12,2019-20,30.0,TOR,NBA,C,55.0,1485.0,17.3,0.583,0.272,...,NaN,1.2,2.7,3.9,0.126,NaN,0.1,0.0,0.1,0.8
13,2020-21,31.0,LAC,NBA,C,41.0,955.0,18.2,0.585,0.315,...,NaN,1.7,1.3,3.0,0.150,NaN,1.3,-0.5,0.8,0.7
14,Career,NaN,NaN,NBA,NaN,849.0,24064.0,17.2,0.571,0.186,...,NaN,34.9,35.9,70.8,0.141,NaN,0.2,0.4,0.6,15.5
15,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,7 seasons,NaN,OKC,NBA,NaN,524.0,15099.0,17.5,0.567,0.105,...,NaN,24.5,23.1,47.6,0.151,NaN,0.1,0.7,0.8,10.7
17,4 seasons,NaN,TOR,NBA,NaN,228.0,6300.0,16.5,0.577,0.288,...,NaN,6.6,9.8,16.4,0.125,NaN,-0.1,0.0,-0.1,3.1
18,1 season,NaN,ORL,NBA,NaN,56.0,1710.0,17.5,0.569,0.304,...,NaN,2.1,1.7,3.8,0.108,NaN,0.9,-0.2,0.7,1.2
19,1 season,NaN,LAC,NBA,NaN,41.0,955.0,18.2,0.585,0.315,...,NaN,1.7,1.3,3.0,0.150,NaN,1.3,-0.5,0.8,0.7

In [88]:
## serilaization
h5_Data.put('obj2',ds,format='table')

In [89]:
## desirialization
h5_Data.select('obj2',where=['index >= 10 and index <= 15'])

,Season,Age,Team,Lg,Pos,G,MP,PER,TS%,3PAr,...,Unnamed: 19,OWS,DWS,WS,WS/48,Unnamed: 24,OBPM,DBPM,BPM,VORP
10,2017-18,28.0,TOR,NBA,PF,76.0,2093.0,14.7,0.574,0.379,...,NaN,2.1,3.0,5.1,0.117,NaN,-0.1,0.0,-0.1,1.0
11,2018-19,29.0,TOR,NBA,C,74.0,2010.0,18.7,0.582,0.193,...,NaN,2.8,3.3,6.1,0.146,NaN,0.2,0.1,0.2,1.2
12,2019-20,30.0,TOR,NBA,C,55.0,1485.0,17.3,0.583,0.272,...,NaN,1.2,2.7,3.9,0.126,NaN,0.1,0.0,0.1,0.8
13,2020-21,31.0,LAC,NBA,C,41.0,955.0,18.2,0.585,0.315,...,NaN,1.7,1.3,3.0,0.150,NaN,1.3,-0.5,0.8,0.7
14,Career,NaN,NaN,NBA,NaN,849.0,24064.0,17.2,0.571,0.186,...,NaN,34.9,35.9,70.8,0.141,NaN,0.2,0.4,0.6,15.5
15,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [90]:
## Data as raw enabled and take from link
df3 = pd.read_csv("https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv")
df3.tail()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.00,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.00,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.45,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.00,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.75,NaN,Q

In [92]:
df3.dtypes

PassengerId      int64
Survived         int64
Pclass           int64
Name            object
Sex             object
Age            float64
SibSp            int64
Parch            int64
Ticket          object
Fare           float64
Cabin           object
Embarked        object
dtype: object

In [93]:
df3.describe()

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,891.000000,891.000000,891.000000,714.000000,891.000000,891.000000,891.000000
mean,446.000000,0.383838,2.308642,29.699118,0.523008,0.381594,32.204208
std,257.353842,0.486592,0.836071,14.526497,1.102743,0.806057,49.693429
min,1.000000,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000
25%,223.500000,0.000000,2.000000,20.125000,0.000000,0.000000,7.910400
50%,446.000000,0.000000,3.000000,28.000000,0.000000,0.000000,14.454200
75%,668.500000,1.000000,3.000000,38.000000,1.000000,0.000000,31.000000
max,891.000000,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200

In [94]:
df3.dtypes == 'object'

PassengerId    False
Survived       False
Pclass         False
Name            True
Sex             True
Age            False
SibSp          False
Parch          False
Ticket          True
Fare           False
Cabin           True
Embarked        True
dtype: bool

In [97]:
df3.dtypes[df3.dtypes== 'object'].index

Index(['Name', 'Sex', 'Ticket', 'Cabin', 'Embarked'], dtype='object')

In [98]:
df3[df3.dtypes[df3.dtypes== 'object'].index]

,Name,Sex,Ticket,Cabin,Embarked
0,"Braund, Mr. Owen Harris",male,A/5 21171,NaN,S
1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,PC 17599,C85,C
2,"Heikkinen, Miss. Laina",female,STON/O2. 3101282,NaN,S
3,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,113803,C123,S
4,"Allen, Mr. William Henry",male,373450,NaN,S
...,...,...,...,...,...
886,"Montvila, Rev. Juozas",male,211536,NaN,S
887,"Graham, Miss. Margaret Edith",female,112053,B42,S
888,"Johnston, Miss. Catherine Helen ""Carrie""",female,W./C. 6607,NaN,S
889,"Behr, Mr. Karl Howell",male,111369,C148,C
890,"Dooley, Mr. Patrick",male,370376,NaN,Q

In [99]:
df5 = df3[df3.dtypes[df3.dtypes== 'object'].index]
df5.describe()

                       Name   Sex  Ticket    Cabin Embarked
count                   891   891     891      204      889
unique                  891     2     681      147        3
top     Canavan, Miss. Mary  male  347082  B96 B98        S
freq                      1   577       7        4      644

In [101]:
df3[['PassengerId','Pclass']]

     PassengerId  Pclass
0              1       3
1              2       1
2              3       3
3              4       1
4              5       3
..           ...     ...
886          887       2
887          888       1
888          889       3
889          890       1
890          891       3

[891 rows x 2 columns]

In [103]:
## As this is a list so u can do all operations in this
## as this is in series format
df3['Name'][5:10]

5                                     Moran, Mr. James
6                              McCarthy, Mr. Timothy J
7                       Palsson, Master. Gosta Leonard
8    Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)
9                  Nasser, Mrs. Nicholas (Adele Achem)
Name: Name, dtype: object

In [104]:
df3['Akash']="Borgalli"

In [105]:
df3

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Akash
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,Borgalli
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,Borgalli
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,Borgalli
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,Borgalli
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,Borgalli
...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S,Borgalli
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S,Borgalli
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S,Borgalli
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C,Borgalli
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q,Borgalli

In [109]:
df3['Akash']=df3['PassengerId']

In [110]:
df3

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Akash
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,1
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,2
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,3
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,4
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S,887
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S,888
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S,889
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C,890
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q,891

In [113]:
pd.Categorical(df3['Sex'])

['male', 'female', 'female', 'female', 'male', ..., 'male', 'female', 'female', 'male', 'male']
Length: 891
Categories (2, object): ['female', 'male']

In [114]:
pd.Categorical(df3['Pclass'])

[3, 1, 3, 1, 3, ..., 2, 1, 3, 1, 3]
Length: 891
Categories (3, int64): [1, 2, 3]

In [115]:
df3['Pclass'].unique()

array([3, 1, 2], dtype=int64)

In [118]:
df3['Pclass'].isnull().count()

891

In [131]:
## row selection where Cabin values are null
ser = df3['Cabin'][df3['Cabin'].isnull() == True]

In [132]:
ser.index

Int64Index([  0,   2,   4,   5,   7,   8,   9,  12,  13,  14,
            ...
            878, 880, 881, 882, 883, 884, 885, 886, 888, 890],
           dtype='int64', length=687)

In [133]:
## row level selection
df3.iloc[ser.index]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Akash
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,1
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,3
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,5
5,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q,6
7,8,0,3,"Palsson, Master. Gosta Leonard",male,2.0,3,1,349909,21.0750,NaN,S,8
...,...,...,...,...,...,...,...,...,...,...,...,...,...
884,885,0,3,"Sutehall, Mr. Henry Jr",male,25.0,0,0,SOTON/OQ 392076,7.0500,NaN,S,885
885,886,0,3,"Rice, Mrs. William (Margaret Norton)",female,39.0,0,5,382652,29.1250,NaN,Q,886
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S,887
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S,889
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q,891

In [130]:
## row level selection
df3.iloc[[1,2,3,8,10,6]]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Akash
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,2
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,3
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,4
8,9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0,0,2,347742,11.1333,NaN,S,9
10,11,1,3,"Sandstrom, Miss. Marguerite Rut",female,4.0,1,1,PP 9549,16.7000,G6,S,11
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S,7

In [134]:
## to find how many records there are null values
len(ser.index)

687

In [146]:
## To find persons name who paid the highest(fare)
df3[df3['Fare'] == max(df3['Fare'])]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Akash
258,259,1,1,"Ward, Miss. Anna",female,35.0,0,0,PC 17755,512.3292,NaN,C,259
679,680,1,1,"Cardeza, Mr. Thomas Drake Martinez",male,36.0,0,1,PC 17755,512.3292,B51 B53 B55,C,680
737,738,1,1,"Lesurer, Mr. Gustave J",male,35.0,0,0,PC 17755,512.3292,B101,C,738

In [147]:
df3[df3['Fare'] == max(df3['Fare'])]['Name']

258                      Ward, Miss. Anna
679    Cardeza, Mr. Thomas Drake Martinez
737                Lesurer, Mr. Gustave J
Name: Name, dtype: object

In [148]:
## Addition of two columns
df3['Addition'] = df3['PassengerId'] + df3['Age']

In [149]:
df3

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Akash,Addition
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,1,23.0
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,2,40.0
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,3,29.0
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,4,39.0
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,5,40.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S,887,914.0
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S,888,907.0
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S,889,NaN
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C,890,916.0
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q,891,923.0

In [152]:
df6 = pd.read_table("https://raw.githubusercontent.com/justmarkham/DAT8/master/data/chipotle.tsv")
df6

,order_id,quantity,item_name,choice_description,item_price
0,1,1,Chips and Fresh Tomato Salsa,NaN,$2.39
1,1,1,Izze,[Clementine],$3.39
2,1,1,Nantucket Nectar,[Apple],$3.39
3,1,1,Chips and Tomatillo-Green Chili Salsa,NaN,$2.39
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",$16.98
...,...,...,...,...,...
4617,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Black Beans, Sour ...",$11.75
4618,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Sour Cream, Cheese...",$11.75
4619,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",$11.25
4620,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Lettu...",$8.75
4621,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",$8.75

In [153]:
df6.dtypes

order_id               int64
quantity               int64
item_name             object
choice_description    object
item_price            object
dtype: object

In [154]:
df7 = pd.read_table("https://raw.githubusercontent.com/justmarkham/DAT8/master/data/beer.txt")
df7

       name calories sodium alcohol cost
0              Budweiser 144 15 4.7 0.43
1                Schlitz 151 19 4.9 0.43
2              Lowenbrau 157 15 0.9 0.48
3             Kronenbourg 170 7 5.2 0.73
4               Heineken 152 11 5.0 0.77
5          Old_Milwaukee 145 23 4.6 0.28
6             Augsberger 175 24 5.5 0.40
7   Srohs_Bohemian_Style 149 27 4.7 0.42
8             Miller_Lite 99 10 4.3 0.43
9         Budweiser_Light 113 8 3.7 0.40
10                 Coors 140 18 4.6 0.44
11           Coors_Light 102 15 4.1 0.46
12        Michelob_Light 135 11 4.2 0.50
13                 Becks 150 19 4.7 0.76
14                  Kirin 149 6 5.0 0.79
15      Pabst_Extra_Light 68 15 2.3 0.38
16                 Hamms 139 19 4.4 0.43
17   Heilemans_Old_Style 144 24 4.9 0.43
18     Olympia_Goled_Light 72 6 2.9 0.46
19           Schlitz_Light 97 7 4.2 0.47

In [ ]:
df8 = pd.read_table("https://raw.githubusercontent.com/guipsamora/pandas_exercises/master/04_Apply/US_Crime_Rates/US_Crime_Rates_1960_2014.csv")
df8

In [ ]:
df9 = pd.read_table("https://raw.githubusercontent.com/vincentarelbundock/Rdatasets/master/datasets.csv")